### ISSUE TITLE
It is normal to hide or close the layer with psd-tools and open it with photoshop, but the PNG generated with psd-tools is not

### ISSUE THREAD

**Issue by TIM952597205** [psd-tools/psd-tools#101]
psd = PSDImage.open('False.psd')
for layer in psd.descendants():
    layer.visible = True
psd.save('True.png')

The resulting PNG is empty

**Comment by kyamagu** [comment]
@TIM952597205 You can only save PSD file. If you need to generate PNG, do `psd.compose().save('True.png')`

**Comment by TIM952597205** [comment]
@kyamagu  I'm sorry I made the wrong copy. Now I'm using psd.compose(). Save ('True. PNG ')  ,The problem is that setting the layer to False or True produces the same PNG ，Let's put it this way: I want to turn on a PSD of a closed image to generate a PNG 。

**Comment by TIM952597205** [comment]
@kyamagu ![1](https://github.com/TIM952597205/Qbook/blob/master/9.png) #

**Comment by kyamagu** [comment]
@TIM952597205 Can you try `psd.compose(force=True).save('True.png')`?

**Comment by TIM952597205** [comment]
@kyamagu Thank you very much. This solves the problem perfectly. However, there is one problem. If force=True with all layers closed, it will say "AttributeError: 'NoneType' object has no attribute 'save'" But that would solve my problem thank you

**Comment by kyamagu** [comment]
@TIM952597205 When no layer is visible, `compose()` will return `None`. Just check the output before saving. Good luck.
