### ISSUE TITLE
Question on saved file size when changing visibility flags

### ISSUE THREAD

**Issue by TIM952597205** [psd-tools/psd-tools#102]
If I close this layer in photoshop it's gonna get smaller and if I close this layer in photoshop it's gonna stay the same size if I close this layer in psd-tools is there a way to do that thank you

**Comment by kyamagu** [comment]
@TIM952597205 I'm not sure what you mean. Can you clarify what you mean by *close this layer*?

**Comment by TIM952597205** [comment]
Hide all the layers

**Comment by kyamagu** [comment]
@TIM952597205 Do you mean:

In Photoshop:
1. File size decreases if a layer is hidden
2. File size stays the same if a layer is visible

And, you wish to achieve case 1) in psd-tools?

Currently this is not possible. Photoshop composes the entire image and saves that inside the file, and that change in pixels affect the final compression size. However, psd-tools does not currently composes the final image before saving, and consequently stays the same in file size. Writing and rendering support in psd-tools is very limited as of now.

To implement the same behavior, psd-tools needs to implement high-quality rendering engine compatible with Photoshop. However that won't happen anytime soon.
