### ISSUE TITLE
Error composing from root psd (AssertionError: len=522694, expected=540000)

### ISSUE THREAD

**Issue by daltonridenhour** [psd-tools/psd-tools#103]
Hi, I am receiving the following error when composing from root psd:  AssertionError: len=522694, expected=540000.  Unfortunately, I am not able to share the .psd;  will try to recreate at a later time (but maybe you will know what is causing the error).  This is only happening for one of many .psds:

```
psd.compose()

File "/env/local/lib/python3.7/site-packages/psd_tools/api/psd_image.py", line 138, in compose

image = self.topil() if (not force or len(self) == 0) else None

File "/env/local/lib/python3.7/site-packages/psd_tools/api/psd_image.py", line 125, in topil

return pil_io.convert_image_data_to_pil(self._record)

File "/env/local/lib/python3.7/site-packages/psd_tools/api/pil_io.py", line 47, in convert_image_data_to_pil

for channel_data in psd.image_data.get_data(header):

File "/env/local/lib/python3.7/site-packages/psd_tools/psd/image_data.py", line 63, in get_data

header.version)

File "/env/local/lib/python3.7/site-packages/psd_tools/compression.py", line 66, in decompress

len(result), length

AssertionError: len=522694, expected=540000
```

Thank you!

**Comment by kyamagu** [comment]
@daltonridenhour Thanks for reporting this.

Unfortunately, this is only telling me that the saved image data is corrupted or in an unknown format. I cannot debug this without test data.

**Comment by daltonridenhour** [comment]
Ok, thank you.  I will try to recreate at some point.

**Comment by daltonridenhour** [comment]
Hi, I have a .psd now for you to test.  Here is the error:

![image](https://user-images.githubusercontent.com/60800/58277448-c3b47d80-7d67-11e9-9c11-3a0273966e01.png)

And the test psd:


[1-1-Spring Sale.psd.zip](https://github.com/psd-tools/psd-tools/files/3213661/1-1-Spring.Sale.psd.zip)


Note that this seems to work locally but fails inside a cloud function.  Any ideas?  Thank you for your help!

**Comment by kyamagu** [comment]
@daltonridenhour I cannot reproduce the same error. Just to make sure, can you upgrade the package in your cloud env? The following is from psd-tools 1.8.15.

<img width="581" alt="2019-05-24 9 37 19" src="https://user-images.githubusercontent.com/1190780/58294940-a20ad300-7e07-11e9-88d5-d27d710b1d33.png">

**Comment by daltonridenhour** [comment]
Sorry for the delay;  I went out of town for a while.  The cloud env is using 1.8.15 and Node v8 (Google Cloud function).  It looks like it might be an issue with smart objects.  Would there be an issue with uploading a .psd to a cloud server and composing a thumbnail when the .psd contains smart objects that are linked to .psb files?  Oddly enough, things are working fine when the smart object layer is composed directly;  the issue only occurs when I try to compose the root.

**Comment by kyamagu** [comment]
@daltonridenhour It seems the embedded preview image is corrupted. I would suggest you check the file checksum to make sure the file is not corrupted.
