### ISSUE TITLE
How to parse scalable vector graphics from psd ?

### ISSUE THREAD

**Issue by rivergold** [psd-tools/psd-tools#105]
How to parse scalable vector graphics from `.psd` using psd-tools? When using `layer.topil()`, it returns `PIL.Image` which is a bitmap. Is there any way to get the raw scalable vector graphics and then I can use other tools to process it?

**Comment by kyamagu** [comment]
[Check the documentation](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.shape.html)
