### ISSUE TITLE
Unable to open PSD file

### ISSUE THREAD

**Issue by BohdanCube** [psd-tools/psd-tools#108]
In one macOS project I had no problem with psd-tools opening PSD files. Today I've found one that I cannot open. File is "vanilla" PSD file and can be opened in Photoshop.

Here is a trace

> Traceback (most recent call last):
>   File "/Users/bohdankubkin/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/ptvsd_launcher.py", line 45, in <module>
>     main(ptvsdArgs)
>   File "/Users/bohdankubkin/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__main__.py", line 391, in main
>     run()
>   File "/Users/bohdankubkin/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__main__.py", line 272, in run_file
>     runpy.run_path(target, run_name='__main__')
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/bohdankubkin/MyRepositories/FPKProjects/PSDComparator/PSD Comparator/PSDParser.py", line 257, in <module>
>     psdData = PSD.read(f)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/__init__.py", line 71, in read
>     LayerAndMaskInformation.read(fp, encoding, header.version),
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/layer_and_mask.py", line 64, in read
>     return cls._read_body(f, encoding, version)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/layer_and_mask.py", line 76, in _read_body
>     tagged_blocks = TaggedBlocks.read(fp, version=version, padding=4)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/tagged_blocks.py", line 158, in read
>     block = TaggedBlock.read(fp, version, padding)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/tagged_blocks.py", line 253, in read
>     data = kls.frombytes(raw_data, version=version)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 262, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 262, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 146, in frombytes
>     value = kls.frombytes(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 142, in frombytes
>     v_token, v_token_type = next(tokenizer)
>   File "/usr/local/lib/python3.7/site-packages/psd_tools/psd/engine_data.py", line 123, in __next__
>     raise ValueError("Unknown token: %r" % (token))
> ValueError: Unknown token: b'()'
> Terminated: 15

**Comment by kyamagu** [comment]
What’s your psd-tools version?

**Comment by BohdanCube** [comment]
> What’s your psd-tools version?

Originally 1.8.8 and now I tried using 1.8.14 but with same results.

**Comment by kyamagu** [comment]
Can you share a file that reproduces this issue?

**Comment by BohdanCube** [comment]
> Can you share a file that reproduces this issue?

Unfortunately, I cannot provide original PSD file. It's confidential. 

My designer team will analyse PSD file in near future. But I can say for sure, that issue is caused by Layer Compositions or some layer type. 

I tried to remove them and file is opened without problem.

Will provide more info when I manage to narrow cause of the problem.

**Comment by kyamagu** [comment]
The issue is likely from the incomplete token regex in the psd.engine_data
module. I appreciate if you can create a erroneous file by removing any
confidential layers.

**Comment by BohdanCube** [comment]
Hello there,

finally after some long long time we managed to get through the issue. Our graphic used text layer with wierd sign. Removing this layer fixed the problem. 

For lib improvement purposes the char inserted was "�". So create empty PSD and add text layer with this char in it. Should 100% reproduce the issue.

If not, I am providing PSD file [wrong_layer.psd.zip](https://github.com/psd-tools/psd-tools/files/3276169/wrong_layer.psd.zip)

**Comment by kyamagu** [comment]
Strange. I have no problem opening the file in psd-tools 1.8.19 / python 3.6.2 / macOS 10.14.5. Is this a locale-specific issue?

<img width="587" alt="screenshot 2019-06-12 12 24 22" src="https://user-images.githubusercontent.com/1190780/59321462-151faf00-8d0d-11e9-855c-717e0fce9229.png">
