### ISSUE TITLE
Prevent layer cropping

### ISSUE THREAD

**Issue by commentsr** [psd-tools/psd-tools#110]
When i do .compose() or .topil() the image is cropped. can i get it in its original canvas size?

**Comment by kyamagu** [comment]
You can specify the bbox option in compose

**Comment by commentsr** [comment]
I tried adding a bbox but it doesnt seem to have any effect. the bbox i provided is the same as my psd canvas size but it still gets cropped

**Comment by kyamagu** [comment]
Can you upload a reproducible sample?

**Comment by commentsr** [comment]
[issue.zip](https://github.com/psd-tools/psd-tools/files/3208897/issue.zip)
Here is an example of it. I want the saved image to be identical to the psd layer, but it gets cropped down.

**Comment by kyamagu** [comment]
@commentsr Thanks for the package. Ver 1.8.15 fixes this issue.
