### ISSUE TITLE
Return wrong blend mode type and can't processing selectivecolor layer

### ISSUE THREAD

**Issue by vnknowledge2014** [psd-tools/psd-tools#113]
Return wrong blend mode type - PASS_THROUGH always be set NORMAL
Layer selectivecolor can't export infomation

**Comment by kyamagu** [comment]
@vnknowledge2014 Likely photoshop internally saves PASS_THROUGH and NORMAL configuration in the same code.

Adjustment layers do not have good support yet. You can check the content by `layer._record` private property.

**Comment by vnknowledge2014** [comment]
well I not surely about "PASS_THROUGH and NORMAL configuration in the same code"
My solution for it:
```
@property
    def blend_mode_group(self):
        """
        Blend mode of this layer. Writable.

        Example::

            from psd_tools.constants import BlendMode
            if layer.blend_mode == BlendMode.NORMAL:
                layer.blend_mode = BlendMode.SCREEN

        :return: :py:class:`~psd_tools.constants.BlendMode`.
        """
        targetBlockSetting = self._record.tagged_blocks.get_data('lsct', None)
        if targetBlockSetting and hasattr(targetBlockSetting, "key") and targetBlockSetting.key:
            return targetBlockSetting.key.name
        return BlendMode.NORMAL
```

I push that snippet into class layer in layers.py file.
And Can you help me or suggest me about the right way to process effect layers in photoshop ?

**Comment by kyamagu** [comment]
@vnknowledge2014 `psd_tools.api` package does not have a good support for effects yet. You can inspect the low level `psd_tools.psd` package to access all the internal data. See docs: https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.psd.html

**Comment by vnknowledge2014** [comment]
I hope your team will have a good solution for it soon :))

**Comment by kyamagu** [comment]
Issue #114 is also due to the lack of blending mode supports
