### ISSUE TITLE
Compose group image error

### ISSUE THREAD

**Issue by vnknowledge2014** [psd-tools/psd-tools#114]
Compose group image error when a layer mix with mask layer has background is white.

**Comment by kyamagu** [comment]
@vnknowledge2014 Composer is far from perfect. Can you upload a erroneous example?

**Comment by vnknowledge2014** [comment]
Many thank, That psd link and error image png when I extract it using compose:
psd: https://ufile.io/sm3rpdvz

Error Images:
Front (group): https://imgur.com/orz4N4w
Front -> More Shadow (group): https://imgur.com/3CglHyo
Front -> More Shadown -> Layer 3 with mask layer: https://imgur.com/J5eYlen

If you can fix it soon, please let me know soon!
Many thank bro :D

**Comment by kyamagu** [comment]
Thanks for the file. This can take some time.
