### ISSUE TITLE
How to determine specific options not implemented in the API?

### ISSUE THREAD

**Issue by Cruaier** [psd-tools/psd-tools#115]
Hi there,
I'd like to determine some options from a PSD file but not all options are implemented in the API (e.g. flattened image, transparency..). You already import the list of options  (https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.terminology.html), I'd like to get a hint on how to implement more options by myself.
Thanks and keep on the good work :)

**Comment by kyamagu** [comment]
@Cruaier 
>> I'd like to get a hint on how to implement more options by myself.

It depends on which data structure you're working on. Typically, you can just use `bytes` to work with unknown items.

**Comment by Cruaier** [comment]
@kyamagu thanks for the prompt answer. As I already use the PSDImage class for other things is there an option to get the right object/bytes from there? So I don't have to read the whole file twice..

**Comment by kyamagu** [comment]
@Cruaier `PSDImage` is a wrapper over underlying `PSD` object, that you can check by `_record` attribute of PSDImage. Typically you can check `tagged_blocks` of individual layers to access necessary info

**Comment by Cruaier** [comment]
@kyamagu I might be on the wrong track but the tagged_blocks don't contain the information I'm looking for. As an example I'm looking for the indicator FlattenImage (https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.terminology.html#psd_tools.terminology.Event.FlattenImage). Following the specification (https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_72092) it is not really clear to me where to find the data or as what they are saved...any idea?

**Comment by kyamagu** [comment]
Basically all the info a file has is in psd._record .  If your desired key
is not contained, that field does not exist in the file.

**Comment by Cruaier** [comment]
you are right, you can filter out all bytes from the class. anyway the option I was looking for was not specified following the specification of the PSD format - even though the file was changed with it.
