### ISSUE TITLE
Compose error saving PSD as Image

### ISSUE THREAD

**Issue by Constuelo** [psd-tools/psd-tools#126]
Attached .psb/.py and image

``` python
from psd_tools import PSDImage

psd = PSDImage.open('gilet.psb')
psd.compose().save('example.png')
```

If it's not obvious, look at the gilet
![example](https://user-images.githubusercontent.com/13840040/61711251-85c5dc80-ad4b-11e9-9896-2df6207008a5.png)

[gilet.zip](https://github.com/psd-tools/psd-tools/files/3421941/gilet.zip)

**Comment by Constuelo** [comment]
I have the latest version of psd-tools

I'll also add, converting the layers into a smart object in the psd fixes the issue however this isn't a solution unless i can do this programmatically, hopefully this issue will improve the .compose() method.

**Comment by Constuelo** [comment]
Update, changing the file type to .psd from .psb fixes this

**Comment by kyamagu** [comment]
@Constuelo Thanks. You could fix by changing from psb to psd probably because you have specified 'maximize compatibility' option. I could reproduce this in psd also.

The error is from unsupported `color` blending mode. Not all of the blending modes are supported as of ver 1.8.23.

**Comment by Constuelo** [comment]
Okay I don't think i can change to `.psd` programmatically, see below.

My process;
- I am saving out a `smartobject` layer to disk (ie the previous attached `.psb`)
  - It automatically saves out as `.psb`
  - When saving out to `.psd` programatically the results are the same
  - When saving out to `.psd` via photoshop it's okay.
- Then opening the file from disk and loading into `PSDImage` then saving

1. In reference to my process above, can i save out the contents of a smartobject programatically with psd-tools?

**Example**:
In my **main** `.psd` i have a `smartobject` which is `100x200` in size
Inside the `smartobject` the size is actually `300x500` (this is the size i need)
If I `smartobject.save()` in my **main** `.psd`, the output would be `100x200`
If i save the `smartobject` as `.psd` and reopen then save, the output would be `300x500`

```
The error is from unsupported color blending mode. Not all of the blending modes are supported as of ver 1.8.23.
```
2. Is there likely going to work/fixes on this in the future? I no your mostly maintaining this repo by yourself (I would help if i new how)

**Comment by kyamagu** [comment]
Something like the following should work to directly opening a smart object. In any case, I do not think Photoshop turns on `maximize compatibility` option for embedded objects, and therefore psd-tools might not correctly render advanced blending modes.

```python
if layer.smart_object.is_psd():
    with layer.smart_object.open() as f:
        embedded_psd = PSDImage.open(f)
```

**Comment by kyamagu** [comment]
@Constuelo ver 1.8.24 improves the quality, though the result is not exactly the same with photoshop. feel free to re-open the issue if there is still a problem
