### ISSUE TITLE
How to export the special effect of PSD text layer?

### ISSUE THREAD

**Issue by F1And** [psd-tools/psd-tools#128]
Hi, dear kyamagu:

   Have been working on some PSD parsing with your open source psd-tools. But when I used a large number of PSD files where the font layer appeared, I was able to Parse the object information for the entire layer.
   You can even get some special effects information on the font, and you can see a description of all the special effects classes in your Docs (https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.effects.html）      
But when I want to go and pull out these special effects information separately, use the other .

![image](https://user-images.githubusercontent.com/37165965/61761346-10b4de80-ae01-11e9-9dfb-3744a21162d3.png)

**Comment by kyamagu** [comment]
You can get individual effects like:
```python
effect = layer.effects[0]
print(effect.value)
```

**Comment by F1And** [comment]
> You can get individual effects like:
> 
> ```python
> effect = layer.effects[0]
> print(effect.value)
> ```
Thanks, I know how to get ```effect.value```.I mean we can get the value but how can I use the effects merge a new picture?

**Comment by kyamagu** [comment]
Composer currently does not support most of the effects

**Comment by harrywang** [comment]
@kyamagu do you know any other packages that provide such effects? Or any other alternative ways of doing that before such support is added to Composer (BTW, do you have any plan of doing that?). We really appreciate your suggestions/comments. Thanks.

**Comment by kyamagu** [comment]
@harrywang You can use Adobe Photoshop' script, or open source alternative such as GIMP.
