### ISSUE TITLE
When CMYK's image that have Alpha channel lost in the project, I fix it.

### ISSUE THREAD

**Issue by F1And** [psd-tools/psd-tools#130]
I looked at the CMYK image processing, and you only put Alpha when mode is RGB or L, so I did it locally. When CMYK has an Alpha layer, you should also put Alpha.

![image](https://user-images.githubusercontent.com/37165965/61863625-8eacde80-af02-11e9-882e-7ae3b399fb1e.png)

**Comment by kyamagu** [comment]
pillow does not support alpha channel for CMYK mode. Do you test this?

**Comment by F1And** [comment]
> pillow does not support alpha channel for CMYK mode. Do you test this?

I have test all cmyk what has alpha in your code.But all alpha missed. when I fix the code I can get it.
Test and verify 4 files. If you want to test your code, I can give you some about CMYK's PSD.

 when psd-tools2==1.7.29 can work. But now I don't know why, so I find it.

**Comment by kyamagu** [comment]
You might be able to `putalpha` on CMYK image, but that implicitly converts the color mode to RGBA in Pillow. This is the limitation of Pillow. The current implementation chooses to return CMYK as is, ignoring alpha.

<img width="728" alt="2019-07-26 14 36 45" src="https://user-images.githubusercontent.com/1190780/61928275-e30f9700-afb2-11e9-9567-161d1d213146.png">

**Comment by F1And** [comment]
I give you a psd that has  alpha channel.

[Uploading 3.psd.zip…](test.zip)

**Comment by F1And** [comment]
In your code the image:
![image](https://user-images.githubusercontent.com/37165965/61933574-ca09e480-afb8-11e9-955f-8f3a3aec23f7.png)

In my code the image
![image](https://user-images.githubusercontent.com/37165965/61933581-d0985c00-afb8-11e9-8e3c-2c783a36bbd4.png)

**Comment by kyamagu** [comment]
@F1And `putalpha()` implicitly converts CMYK to RGBA in Pillow. The current implementation tries to return the original CMYK representation, and due to the limitation in Pillow, we can't support CMYK+alpha in `topil` or `compose` methods.

**Comment by kyamagu** [comment]
Perhaps one possibility is to prepare an api to return an individual channel.

**Comment by F1And** [comment]
Thank you, and we would appreciate it if you could provide such an API. If we can't, we'll have to add an API for this scenario, which would be inconvenient.

**Comment by duwangthefirst** [comment]
FINALLY found the solution, in case anyone may need it:

```python
from psd_tools import PSDImage
from PIL import Image
from psd_tools.constants import ChannelID

psd = PSDImage.open(psd_path)
for index, layer in enumerate(psd):
    image = layer.topil()
    alpha_channel = layer.topil(ChannelID.TRANSPARENCY_MASK) if image.mode == "CMYK" else None
    image = image.convert("RGBA")
    if alpha_channel:
        r, g, b, a = image.split()
        image = Image.merge("RGBA", [r, g, b, alpha_channel])
    image.save('{}.png'.format(index))

```
