### ISSUE TITLE
Usage of metadata tagged blocks

### ISSUE THREAD

**Issue by sona1111** [psd-tools/psd-tools#131]
(this is a follow up to issue https://github.com/kyamagu/psd-tools/issues/100)

Note that I am using the "psd-tools2" version -- if this is incorrect please let me know and I can switch to the standard "psd-tools" library. 

My usage goal is to attach a UUID (36 character string) to a layer in a PSD file, and be able to read it back later. 

In the linked issue there was an explanation regarding writing and reading metadata tagged blocks, which I will summarize here:

```
psd = PSDImage.open('tests/psd_files/colormodes/4x4_8bit_rgb.psd')
layer = psd[0]
metadata = layer.tagged_blocks.get_data(Tag.METADATA_SETTING)

item = psd_tools.psd.tagged_blocks.MetadataSetting(key=b'plug', data=b'0xFF')
metadata.append(item)

psd.save('output.psd')
```

This code seems to work if the metadata setting block has already been created by some process before (for example the method I have used in the old post), but not if the file is new / blank. In this case, when I call get_data (above, third line) the value of "metadata" is "None", and therefore I can not append to it. In the case that the metadata tagged block was not created before, how are we intended to create it?

**Comment by kyamagu** [comment]
@sona1111 You can probably try the following:

```python
metadata = psd_tools.psd.tagged_blocks.MetadataSettings()
item = psd_tools.psd.tagged_blocks.MetadataSetting(key=b'plug', data=b'0xFF')
metadata.append(item)
layer.tagged_blocks.set_data(Tag.METADATA_SETTING, metadata)
```

This is highly experimental and you should not use this in production.

**Comment by kyamagu** [comment]
`psd-tools2` is now merged to `psd-tools`, and `psd-tools2` is discontinued

**Comment by sona1111** [comment]
@kyamagu 

Thank you, I really appreciate you quickly following up on my question. For your comment about it being "highly experimental" , I respect your caution, but I don't feel this warning is really quantifiable without additional context. I intend to use this functionality in "production", but I also intend to report back with reproducible examples of an issue if I find a bug and/or provide a fix for them myself. Hopefully we can improve the usable scope of the library over some time. ^_^

Thank you again for the assistance, it has been very helpful!
