### ISSUE TITLE
Create psd and mock the layer is ok?

### ISSUE THREAD

**Issue by bianchengxiaosheng** [psd-tools/psd-tools#132]
I want to create a psd ,and add group ,pixellayer,textlayer by code,the current version can achieve these function?

**Comment by kyamagu** [comment]
Nope. [See what's possible in the documentation](https://psd-tools.readthedocs.io/en/latest/#features)

**Comment by bianchengxiaosheng** [comment]
i see thc document have **Read and write of the low-level PSD/PSB file structure;**,but i dont find example in test
