### ISSUE TITLE
Layer bbox wrong

### ISSUE THREAD

**Issue by zhouweidong** [psd-tools/psd-tools#134]
Dear
I parsed a psd by psd-tools. print all layer name and bbox. but layer named "格子" got bbox is (162, 81, 2289, 3233),  by layer.compose() , I got a image, but the image size is "2480x3508".
Is something wrong? 
Here is the psd file.
https://drive.google.com/open?id=1bRQ6ODpQ4dnLbzlvzRjNwB4mIvyzhSOS
Sorry for some Chinese words.

**Comment by kyamagu** [comment]
@zhouweidong This behavior happens when the mask background is white (making a hole). In this case, Photoshop exports the layer with the canvas size rather than the layer size, and psd-tools follows this behavior. If you really need to crop to the layer size, do the following:

```python
layer.compose(bbox=layer.bbox)
```

**Comment by zhouweidong** [comment]
> @zhouweidong This behavior happens when the mask background is white (making a hole). In this case, Photoshop exports the layer with the canvas size rather than the layer size, and psd-tools follows this behavior. If you really need to crop to the layer size, do the following:
> 
> ```python
> layer.compose(bbox=layer.bbox)
> ```

It's worked for me. thank you.
