### ISSUE TITLE
How to export an image without typelayer

### ISSUE THREAD

**Issue by zhouweidong** [psd-tools/psd-tools#135]
Dear.
I have a requirement. I want export an image expect typelayer. after that i can redraw text on the image. but group layer can not remove sublayer.  Is there any way to export an image without typelayer?

**Comment by kyamagu** [comment]
@zhouweidong You can flag invisible and force composition:

```python
for layer in psd.descendants(include_clip=True):
    if layer.kind == 'type':
        layer.visible = False
        
psd.compose(force=True)
```

**Comment by zhouweidong** [comment]
> @zhouweidong You can flag invisible and force composition:
> 
> ```python
> for layer in psd.descendants(include_clip=True):
>     if layer.kind == 'type':
>         layer.visible = False
>         
> 
> ```

When some group have mask in psd. 'psd.compose(force=True)' export a  image is not the right. Is it a bug or I am wrong? Here is the pad and export image.
https://drive.google.com/open?id=1a27ZgDtezyPQAkl484gwpo-PO0bYXRBD

**Comment by kyamagu** [comment]
Likely a bug, will investigate

**Comment by kyamagu** [comment]
Should be fixed in v1.8.26

**Comment by zhouweidong** [comment]
Thank your.

**Comment by zhouweidong** [comment]
> @zhouweidong You can flag invisible and force composition:
> 
> ```python
> for layer in psd.descendants(include_clip=True):
>     if layer.kind == 'type':
>         layer.visible = False
>         
> psd.compose(force=True)
> ```

Dear according this function. this psd export a png not same with the psd. Can you help to check.
Here is the psd address: https://drive.google.com/open?id=1zGqlk_uzBQI56NMJg9gfG1oOv6LfPKqW

**Comment by yoyoshuang** [comment]
I also come across this problem, my version num is 1.8.30， and the psd file is [https://drive.google.com/file/d/1SsQ-YRUytXARaTAcI1d66SZ8bBsHsSBm/view?usp=sharing](url) and it show out like this 

![kkk](https://user-images.githubusercontent.com/26050950/66909103-c24d5f80-f03e-11e9-96fe-e60fb53541d2.png)

when i remove the group which has the mask layer, it show right, I want to know the problem.

right pic

![background](https://user-images.githubusercontent.com/26050950/66909223-f32d9480-f03e-11e9-9eb4-2bb6c3ebf513.png)

**Comment by kyamagu** [comment]
@yoyoshuang This is a different issue, go to #151
