### ISSUE TITLE
Allow specifying file encoding to PSDImage.open

### ISSUE THREAD

**Issue by lbeltrame** [psd-tools/psd-tools#137]
Rationale: a few PSDs made by Japanese users which still use Shift-JIS encoding for layer names. Unless one specifically sets Shift-JIS, the layer names become all mojibake.

**Comment by lbeltrame** [comment]
The same should be done for `write()` or it won't work at all.

**Comment by kyamagu** [comment]
Interesting. I am regularly working with Japanese environment but do not observe shift-jis files. Can you share any example? I guess recent Photoshop saves layer names in unicode.

**Comment by lbeltrame** [comment]
This is the PSD file I got asked by someone to fix (aka: make the layer names into something readable), the one that prompted me to file this bug report. Unfortunately, as it was found on Twitter / Nicovideo it's kind of convoluted to get: http://whitecats.dip.jp/up/download/1531773189/attach/ and uses a password ("sora").

**Comment by kyamagu** [comment]
@lbeltrame v1.8.27 release takes additional encoding param in `open` and `save`.

```python
psd = PSDImage.open(filename, encoding='shift-jis')
```

It seems the PSD file is not created by Adobe Photoshop. There is no information on what program generated the concerned file.

**Comment by lbeltrame** [comment]
Finding information about it is scarce, but it might be Clip Studio or a similar application.
