### ISSUE TITLE
@zhouweidong You can flag invisible and force composition:

### ISSUE THREAD

**Issue by zhouweidong** [psd-tools/psd-tools#139]
@zhouweidong You can flag invisible and force composition:

```python
for layer in psd.descendants(include_clip=True):
    if layer.kind == 'type':
        layer.visible = False
        
psd.compose(force=True)
```

_Originally posted by @kyamagu in https://github.com/psd-tools/psd-tools/issues/135#issuecomment-525538565_

Dear according this function. this psd export a png not same with the psd. Can you help to check.
Here is the psd address: https://drive.google.com/open?id=1zGqlk_uzBQI56NMJg9gfG1oOv6LfPKqW

**Comment by kyamagu** [comment]
@zhouweidong Are you talking about layer effects? [As stated in documentation](https://psd-tools.readthedocs.io/en/latest/#features), not all photoshop features including layer effects are available as of now. Try not using layer effects and see if that reproduce the view.
