### ISSUE TITLE
Cant get effects data 

### ISSUE THREAD

**Issue by kratosvn** [psd-tools/psd-tools#140]
Hi guy, can you help me check a bug `Unable to get repr for <class 'psd_tools.api.effects.Effects'>`.
I want to get scale and rotate the effect of layer print_front.

![image](https://user-images.githubusercontent.com/14298385/64471005-19c1fb00-d176-11e9-94ca-4ea5075d3189.png)

**Comment by kratosvn** [comment]
here is my psd file
[hoodie_back-flatten.zip](https://github.com/psd-tools/psd-tools/files/3586341/hoodie_back-flatten.zip)

**Comment by kyamagu** [comment]
Thanks for reporting this, please upgrade to v1.8.28
