### ISSUE TITLE
Can you parse the clipping mask information of PSD file?

### ISSUE THREAD

**Issue by wintercat1994** [psd-tools/psd-tools#147]

**Comment by kyamagu** [comment]
@wintercat1994 [See documentation](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.PixelLayer.clip_layers)

**Comment by wintercat1994** [comment]
> @wintercat1994 [See documentation](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.PixelLayer.clip_layers)

Thank you very much for your reply.I'm sorry but there's still something I don't understand.The clipping mask I mentioned refers to the situation:layer 1 is a clipping mask for layer 2, in which the coordinates of the pixels in layer 1 whose RGB values are not empty constitute a mask,and use this mask as layer 2's mask,to mask part of layer 2.Is clip_mask the same thing in your code?

**Comment by kyamagu** [comment]
@wintercat1994 Same thing. Any layer marked clipping mask goes to each layer's clip_layers attribute.
