### ISSUE TITLE
Retrieve a color from a psd_tools.api.layers.ShapeLayer

### ISSUE THREAD

**Issue by Constuelo** [psd-tools/psd-tools#148]
Hi

I'd like to retrieve the color in the below image, I can't see how to get the raw data of a shape layer from the documentation.

The `Rectangle` is a shape layer
Double click into the layer reveals the color panel

![image](https://user-images.githubusercontent.com/13840040/65817960-d3a40880-e204-11e9-86a6-f12459feabcc.png)

**Comment by Constuelo** [comment]
Alright this is what I figured in the end
```                
shapelayer_data = layer.tagged_blocks.get_data(Tag.SOLID_COLOR_SHEET_SETTING)._items[b'Clr ']
color_array = []
for k, v in shapelayer_data.items():
    color_array.append(round(int(v)))

return rgb_to_hex(tuple(color_array))
```
Is there a better / easier way to do this?

**Comment by kyamagu** [comment]
@Constuelo There isn't a unified API yet for supporting this. In Photoshop, shape layers are internally fill layer with vector masks, and the fill information is saved in one of color, pattern, or gradient sheet setting as you already did.
