### ISSUE TITLE
How to parse filter applied to a layer?

### ISSUE THREAD

**Issue by proactive-developer** [psd-tools/psd-tools#150]
I applied a specific filter and effect to a layer, attached test image below.
![photoshop_filter](https://user-images.githubusercontent.com/54161219/66013688-b28e3100-e4fe-11e9-83c0-0db77b7ca86c.png)

I could parse effect information, for example, Stroke effect but not sure how to get filter information.

What apis are for parsing filters?

**Comment by kyamagu** [comment]
Filter info is likely in low-level `tagged_blocks` structure. [Check `tagged_blocks` attr](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.PixelLayer.tagged_blocks).

**Comment by proactive-developer** [comment]
@kyamagu Thanks for your kind answer.

I checked the tagged_blocks but look like there are not filter information in tagged_blocks.

I think that filter information are not stored in the PSD file.
Let's say we apply a filter to layer, save it, and close Photoshop.
If we reopen that file, we cannot revert it to the original image.

That is just my idea and what do you think about this?

**Comment by proactive-developer** [comment]
> Filter info is likely in low-level `tagged_blocks` structure. [Check `tagged_blocks` attr](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.PixelLayer.tagged_blocks).

**Comment by proactive-developer** [comment]
> Filter info is likely in low-level `tagged_blocks` structure. [Check `tagged_blocks` attr](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.PixelLayer.tagged_blocks).

@kyamagu Thanks for your kind answer.

I checked the tagged_blocks but look like there are not filter information in tagged_blocks.

I think that filter information is not stored in the PSD file.
Let's say we apply a filter to layer, save it, and close Photoshop.
If we reopen that file, we cannot revert it to the original image.

This is just my idea and what do you think about this?

**Comment by kyamagu** [comment]
@proactive-developer That is probably true, only irreversible filtered pixels are stored in each layer. To get irreversible filter effects, you should use smart filters. That info should be stored in layer's tagged blocks.
