### ISSUE TITLE
Blend modes lighter/darker color incorrectly compose

### ISSUE THREAD

**Issue by kyamagu** [psd-tools/psd-tools#151]
I also come across this problem, my version num is 1.8.30， and the psd file is [https://drive.google.com/file/d/1SsQ-YRUytXARaTAcI1d66SZ8bBsHsSBm/view?usp=sharing](url) and it show out like this 

![kkk](https://user-images.githubusercontent.com/26050950/66909103-c24d5f80-f03e-11e9-96fe-e60fb53541d2.png)

when i remove the group which has the mask layer, it show right, I want to know the problem.

right pic

![background](https://user-images.githubusercontent.com/26050950/66909223-f32d9480-f03e-11e9-9eb4-2bb6c3ebf513.png)

_Originally posted by @yoyoshuang in https://github.com/psd-tools/psd-tools/issues/135#issuecomment-542626964_

**Comment by kyamagu** [comment]
This error happens because solid color fill layer (`Color overlay`) has `darker color` blend mode, which is not yet supported on psd-tools

**Comment by kyamagu** [comment]
Different blend mode works, such as `darken`.

```python
import psd_tools
psd = psd_tools.PSDImage.open('V2.psd')
psd[3][1].blend_mode = psd_tools.constants.BlendMode.DARKEN
image = psd.compose(force=True)
image
```

![download](https://user-images.githubusercontent.com/1190780/67349030-b3583700-f581-11e9-988c-74b2f033f255.png)


The problem is that, there is no good documentation (and its math) on how lighter/darker color blending modes are implemented within photoshop.

**Comment by hazarek** [comment]
All image processing operations can be performed with "Numpy" or "Opencv". I think you should give priority to layer write support.
Photoshop blending formulas;
http://www.simplefilter.de/en/basics/mixmods.html
http://www.deepskycolors.com/archive/2010/04/21/formulas-for-Photoshop-blending-modes.html

The following process is more effective than psd-tools;

`Save the file as .ora with Krita` > `Read ora layers with python` > `Do something with layers` > `Write ora file.`

**Comment by kyamagu** [comment]
Relevant #49 

Blending formula
https://wwwimages2.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_1-7.pdf
