### ISSUE TITLE
How to access Fill value

### ISSUE THREAD

**Issue by alesvaupotic** [psd-tools/psd-tools#152]
Hi,
I would like to access the Fill value of a layer and just can't find the correct attribute. Can somebody please point me in the right direction? Thanks in advance for any code samples!

![ps_fill](https://user-images.githubusercontent.com/1660347/67659878-c42bf280-f95d-11e9-87b9-20e79d604bd5.jpg)

**Comment by kyamagu** [comment]
Try the following

```python
from psd_tools.constants import Tag
layer.tagged_blocks.get(Tag.BLEND_FILL_OPACITY)
```

**Comment by alesvaupotic** [comment]
Thanks, works like a charm!
