### ISSUE TITLE
Cannot parse on 16 or 32 bit

### ISSUE THREAD

**Issue by aleczratiu** [psd-tools/psd-tools#160]
Hi,
I have an issue with parsing a psd file on 16 or 32 bit, the layers property is empty array. When I work with 8 bits psd file all seems to be fine. 

![Screenshot 2019-11-27 at 11 00 59](https://user-images.githubusercontent.com/33958032/69709036-53672a00-1105-11ea-98c7-84ff42c6e0d1.png)

And some deprecation warnings:

```
/Users/_/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py:214: DeprecationWarning: 'he
ader' is deprecated
  attr = getattr(var, name)
/Users/_/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py:214: DeprecationWarning: 'im
age_resource_blocks' is deprecated
  attr = getattr(var, name)
/Users/_/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py:214: DeprecationWarning: 'pa
tterns' is deprecated
  attr = getattr(var, name)
```

**Comment by kyamagu** [comment]
@aleczratiu 16-/32-bit files have a different low-level structure. Can you share any example file that fails to parse?

**Comment by aleczratiu** [comment]
@kyamagu sure. 3 samples on 16 bit which does not work.
[psd_files_16_bit.zip](https://github.com/psd-tools/psd-tools/files/3896019/psd_files_16_bit.zip)

**Comment by kyamagu** [comment]
@aleczratiu Thanks, now fixed in v1.8.32

**Comment by aleczratiu** [comment]
@kyamagu It doesn't work. 
I saw you changed just the `test file` and the `__init__ file` also was changed with some variables for Tag.LAYER_16, Tag.LAYER_32. 
I run the parse psd file example from your repo and it seems to be empty array:

```
from psd_tools import PSDImage

psd = PSDImage.open('./psds/16bit_psd_saved_from_ps_cc_20_0_4.psd')

print(psd);

for layers in psd:
    print(layers)
```

**Comment by kyamagu** [comment]
Upgrade the pip package, do not use the github source

**Comment by aleczratiu** [comment]
@kyamagu  It works 🙂 thank you.

![Screenshot 2019-12-01 at 16 26 53](https://user-images.githubusercontent.com/33958032/69915455-bb947380-1457-11ea-8439-6389171de64f.png)
