### ISSUE TITLE
Where can i find the pen path of TypeLayer

### ISSUE THREAD

**Issue by bottle1125** [psd-tools/psd-tools#162]
I made a text layer using pen tools, like this:
![image](https://user-images.githubusercontent.com/17687367/70027176-86655e00-15dc-11ea-8c2f-6ba969ce3699.png)
I already found the path data in Resource.WORKING_PATH or Resource.PATH_INFO, but I couldn't relate it with the specific text layer.

Hope you can give me some suggestions. Thanks

**Comment by kyamagu** [comment]
@bottle1125 I have no idea. Perhaps you can inspect `tagged_blocks` of the specific layer?

**Comment by bottle1125** [comment]
> @bottle1125 I have no idea. Perhaps you can inspect `tagged_blocks` of the specific layer?

Yes, I have inspected that but failed to find any useful information...Well, I will try some other ways. Anyway, thanks for your reply.

**Comment by Source-Code-Sivir** [comment]
in the total psd tagged_blocks there is a tag called Tag.TEXT_ENGINE_DATA and you can find every type layer's path data in index [0][8][0], so it is a list , for every item in the list , its cubic bezier curve info stored in item[0][1][0], and the start and end point info in item[0][2][6]
