### ISSUE TITLE
How can I get the color of an Artboard.

### ISSUE THREAD

**Issue by orsiluk** [psd-tools/psd-tools#163]
I managed to extract the color of the artboard if it is a PSDImage type but when it is an artboard I can't find it anywhere. From the PSDImage it was in the `tagged_blocks` but for the Artboard it's not there anymore.

**Comment by orsiluk** [comment]
I figured it out, it was under `._psd.tagged_blocks`

**Comment by kyamagu** [comment]
`._psd.tagged_blocks` is essentially `PSDImage`'s tagged blocks. `._psd` private attribute is just a pointer to `PSDImage`.
