### ISSUE TITLE
How to get larger thumbnail ?

### ISSUE THREAD

**Issue by ChinaSilence** [psd-tools/psd-tools#164]

**Comment by kyamagu** [comment]
Can you provide more details?

**Comment by ChinaSilence** [comment]
```
thumbnail = PSDImage.open('test.psd').thumbnail()
```
the thumbnail's width is 160, how can I set the width to get a larger image

**Comment by kyamagu** [comment]
thumbnail() returns embedded image in the PSD file. You should instead use `compose()`.
