### ISSUE TITLE
Add option for extract_bbox function to include invisible layers in calculation 

### ISSUE THREAD

**Issue by JamesPhillips-scoota** [psd-tools/psd-tools#165]
Hello!

Recently, I updated our systems from psd-tools 1.4 to the latest version. However, one change that did throw a spanner in the works was the addition of `layer.is_visible()` in the `Group.extract_bbox` method. https://github.com/psd-tools/psd-tools/blob/57a75be5bcd0ff57b2bedab9a28ea08569a3a5f1/src/psd_tools/api/layers.py#L574

For our Use Case, we need our `Group` layers to include the invisible layers in their calculation. Would it be possible to add an optional parameter when opening a PSD file (or wherever you feel is appropriate) to set a flag and include invisible layers in Bbox calculations?

Thank you for your time.

**Comment by kyamagu** [comment]
@JamesPhillips-scoota Sure, will consider additional option

**Comment by kyamagu** [comment]
@JamesPhillips-scoota Please upgrade via `pip install -U psd-tools`

**Comment by JamesPhillips-scoota** [comment]
Hello again!

Thank you for your speedy response and implementation! I am happy that you are receptive to having invisible layers included in Bbox calculations. I read over the PR and, while the option is added in the `extract_bbox` method, I was also hoping it could be a kwarg that was could pass in to `PSDImage.open` 
https://github.com/psd-tools/psd-tools/blob/1ac7de2bfec133aae6f70c47e4955d608376426e/src/psd_tools/api/psd_image.py#L93

to include all invisible layers when unpacking a PSD. Is that possible?

Thank you again,
James

**Comment by kyamagu** [comment]
I don’t understand, all layers including invisible ones are already parsed

**Comment by JamesPhillips-scoota** [comment]
Sorry for not explaining well. 

As an example, a PSD will have several layers when we read it in and build the `PSD` object. Lets say one layer is a `Group` Layer, which has 1 visible and 2 invisible layers underneath it. Currently, that Group layer, contained inside the overall PSD, will have a Bbox calculation that only factors in the 1 visible layer and ignores the dimensions of the other two layers, as there is no way to set the `extract_bbox` flag when calling `PSDImage.open`. Does that make sense?

**Comment by kyamagu** [comment]
Still don’t understand. Group.extract_bbox method can take PSDImage object

**Comment by JamesPhillips-scoota** [comment]
I'll try to do a code example.

Currently, we might do something like this:

```
from psd_tools import PSDImage

psd = PSDImage.open('c:/my_directory/psd_creative_with_invisible.zip')
for layer in psd:
    print("Layer's Left Value")
    # currently will ignore invisible sub-layers in bbox calculation
    print(layer.left)
```



With only a flag on the extract_bbox method, the code would have to be like this:

```
from psd_tools import PSDImage
from psd_tools.api.layers import Group

psd = PSDImage.open('c:/my_directory/psd_creative_with_invisible.zip')
for layer in psd:
    # if it's a group, the bbox will be incorrect as it was internally set to include_invisible=False, so we have to calculate it again
    if isinstance(layer, Group):
        recalculated_bbox = Group.extract_bbox(layer, include_invisible=True)
        left = recalculated_bbox[0]
    else:
        left = layer.left
    print("Layer's Left Value")
    print(left)
```

In the proposed change, you could do this:

```
from psd_tools import PSDImage

# setting a flag when we open the file means that when we iterate through, each layer we view will have correct values already calculated
psd = PSDImage.open('c:/my_directory/psd_creative_with_invisible.zip', include_invisible=True)
for layer in psd:
    print("Layer's Left Value")
    print(layer.left)
```

**Comment by kyamagu** [comment]
Don't get, you can do the following.

```
bbox_everything = Group.extract_bbox(psd, include_invisible=True)

for layer in psd:
    bbox_layer = Group.extract_bbox(layer, include_invisible=True)
```

**Comment by JamesPhillips-scoota** [comment]
Hmm, I see what you mean, any layer can be passed into extract_bbox and be handled appropriately. This works for our approach in any case.

Thank you for your time on this, I appreciate it. The additional option you have added will make life much easier!
