### ISSUE TITLE
Why adjustmentLayer fail to be exported as images?

### ISSUE THREAD

**Issue by fpgdev** [psd-tools/psd-tools#168]
I used the following code for creating images of group layers. Something went wrong when Adjustment Layer were exporting. Like Curves and Color Balance were fail to be exported, so that the final exported image was viewed differently from it is in PSD. Could you please help me to take a look?
```
im = groupLayer.compase()
im.save('test.png')
```
[test.psd](https://drive.google.com/file/d/1YkrgPZ6XbvKhkeDVrQaBVJwvbn4i-lNI/view)
code exported
![psd-tools export](https://user-images.githubusercontent.com/15614037/70588798-df4e7b00-1c08-11ea-9f65-c8e3d5625b69.png)
photoshop exported
![ps-export](https://user-images.githubusercontent.com/15614037/70588773-ce056e80-1c08-11ea-833f-08d73b20a947.jpg)

**Comment by kyamagu** [comment]
@fpgdev Adjustment layers are not supported as of now

**Comment by fpgdev** [comment]
> @fpgdev Adjustment layers are not supported as of now
Thank you for your reply, do you think there are other ways to achieve this? For example PLI

**Comment by kyamagu** [comment]
One obvious approach is to use Photoshop scripting

**Comment by fpgdev** [comment]
> One obvious approach is to use Photoshop scripting

@kyamagu  got it, thanks

**Comment by kyamagu** [comment]
@fpgdev Good. [FYI, there is a python interface](https://github.com/kyamagu/photoshop-connection)
