### ISSUE TITLE
Is resizing on an psd file possible?

### ISSUE THREAD

**Issue by uday82** [psd-tools/psd-tools#174]
Is there any I can resize an opened psd file. I have tried changing the width and height in FileHeader, it resizes the canvas size and vector layer not the text and rasterized layers. Any help is much appreciated

**Comment by kyamagu** [comment]
@uday82 You cannot resize the PSD file, but you can export a rasterized image and resize:

```python
psd = PSDImage.open('input.psd')
image = psd.compose()
image.resize((256, 256)).save('output.png')
```
