### ISSUE TITLE
Possible to access Layer Index property?

### ISSUE THREAD

**Issue by JamesPhillips-scoota** [psd-tools/psd-tools#175]
In older versions of PSD Tools, it was possible to access each layers Index value via a `._index` attribute. However, in the current version, I haven't been able to find this value anywhere. Is it still possible to access this value? If it isn't, could this value be made accessible?

Thank you.

**Comment by kyamagu** [comment]
@JamesPhillips-scoota Are you talking about [`layer_id`](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.PixelLayer.layer_id) property?
