### ISSUE TITLE
How did the principle of PSD effects come about？

### ISSUE THREAD

**Issue by CachCheng** [psd-tools/psd-tools#179]

**Comment by kyamagu** [comment]
What exactly is the issue?

**Comment by CachCheng** [comment]
How can we get the principle of  PSD font effects?

**Comment by kyamagu** [comment]
What kind of font effects? Like spacing?

**Comment by CachCheng** [comment]
such as:
dropshadow
outerglow
(original)
patternoverlay
gradientoverlay
coloroverlay
innershadow
innerglow
bevelemboss
satin
stroke
how to implement these algorithms？

**Comment by kyamagu** [comment]
I do not know how photoshop implements layer effects. In psd-tools you can
find effect params in effects field
