### ISSUE TITLE
How to get font data? eg.Font names, sizes, and colors

### ISSUE THREAD

**Issue by canghaiyunfan** [psd-tools/psd-tools#192]
Thanks for your great job!
     How to get font data of TypeLayer? eg.Font names, sizes, and colors.

**Comment by kyamagu** [comment]
@canghaiyunfan [Check the documentation](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#psd_tools.api.layers.TypeLayer)

**Comment by canghaiyunfan** [comment]
@kyamagu I have found it. Thank you.
