### ISSUE TITLE
Sizes of shape layers

### ISSUE THREAD

**Issue by grumpygamer** [psd-tools/psd-tools#197]
I'm still struggling with incorrect bounds for rectangle shape layers.  I have a shape layer that goes from the left of the canvas to 2000px. In PS it is from 0,0 and width of 2000px, height of 240px.  When I run psd-tools and look at the bounds (layer.bbox) I get -2,-1,2001,241.  If I rasterize the shape layer I get the correct bbox size.  

There are no strokes or any layer effects on the shapes, they are plain rectangle shapes of a solid color.

I am using psd-tools 1.8.36. 1.9.x seems to have the same behavior with this test file.

A minimal file that exhibits the problem can be found at:

https://www.dropbox.com/s/8ij0of5o6cujmml/Test.psd?dl=0

**Comment by kyamagu** [comment]
@grumpygamer When a PSD file is saved with 'Maximize compatibility' option, Photoshop internally saves pre-composited pixels inside layers. psd-tools exports these pixels when available, and they might have extra padding. I don't know how Photoshop calculates such padding, but `layer.bbox` returns the size from this pre-composited pixels when avail.

If you really need to extract vector information from the shape layer, you can probably do the following. Shape layers hold coordinates in `vector_mask`, and they have bbox in relative coordinates.

```python
layer = psd[1][0]
bbox = (
    round(layer.vector_mask.bbox[0] * psd.width),
    round(layer.vector_mask.bbox[1] * psd.height),
    round(layer.vector_mask.bbox[2] * psd.width),
    round(layer.vector_mask.bbox[3] * psd.height),
)
bbox
```

**Comment by grumpygamer** [comment]
Thank you. This solved the problem perfectly.
