### ISSUE TITLE
1.9 composite export shap bug

### ISSUE THREAD

**Issue by wushiwein119** [psd-tools/psd-tools#207]
![形状 1 拷贝 4](https://user-images.githubusercontent.com/1711891/76774738-4880f400-67df-11ea-9292-b5f20fec9137.png)
1.9 composite export this pic like:
![形状 1 拷贝 4](https://user-images.githubusercontent.com/1711891/76774854-71a18480-67df-11ea-95a2-fe6aad18ecdc.png)
1.8 compose export right

**Comment by kyamagu** [comment]
@wushiwein119 Can you share a reproducible example?

**Comment by wushiwein119** [comment]
[psd_10.zip](https://github.com/psd-tools/psd-tools/files/4341095/psd_10.zip)


> @wushiwein119 Can you share a reproducible example?

**Comment by wushiwein119** [comment]
by the way,i have another question. for example: 'pic = layer.compsite()' .How do I change pic into base64 string, that can be use in html; i try to use tobytes() and base64.b64encode()，but i failed, It doesn't work

**Comment by kyamagu** [comment]
@wushiwein119 
> by the way,i have another question.

This is a off topic, but you can use PIL's `save()` method to export in whatever image format, and encode in base64.
