### ISSUE TITLE
different results for composer and composite

### ISSUE THREAD

**Issue by canghaiyunfan** [psd-tools/psd-tools#209]
when layer layer.blend_mode = BlendMode.OVERLAY,  composer and composite can get different results. I find them use different calculation methods.
composer:
@register(BlendMode.HARD_LIGHT)
 @register(Enum.HardLight)
 def _hard_light(Cs, Cb):
    index = Cs > 0.5
    B = _multiply(Cs, Cb)
    B[index] = _screen(Cs, Cb)[index]
    return B

composite:
def hard_light(Cb, Cs):
    index = Cs > 0.5
    B = multiply(Cb, 2 * Cs)
    B[index] = screen(Cb, 2 * Cs - 1)[index]
    return B

I can get the correct results by composite. May be a bug for composer, please confirm it.

**Comment by kyamagu** [comment]
yes, composite() is the correct implementation. compose becomes deprecated
and removed in the future

**Comment by canghaiyunfan** [comment]
Thanks!
Why remove the compose ? it's  faster than composite. 
In addition, we can compose layer  by compise([layer1, layer2]), but composite() can't.

**Comment by kyamagu** [comment]
compose() implementation was inaccurate in terms of the quality. If you
have a lot of transparent layers, compose() likely results in wrong color
and alpha.

Performance improvement is another issue.
