### ISSUE TITLE
 What is the minimum version of photoshop that psd-tools depends on

### ISSUE THREAD

**Issue by wushiwein119** [psd-tools/psd-tools#213]
What is the minimum version of photoshop that psd-tools depends on

**Comment by kyamagu** [comment]
@wushiwein119 I don't know. Adobe does not publish detailed info on PSD format and Photoshop version correspondence. psd-tools parses PSD structure described in the following document.

https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/
