### ISSUE TITLE
blend modes overlay incorrectly compose

### ISSUE THREAD

**Issue by canghaiyunfan** [psd-tools/psd-tools#221]
When layer. blend_mode = BlendMode.OVERLAY, it can't incorrectly compose.

Attached test psd file.
[test.psd.zip](https://github.com/psd-tools/psd-tools/files/4602547/test.psd.zip)

**Comment by kyamagu** [comment]
What is the psd-tools version?

**Comment by canghaiyunfan** [comment]
psd-tools version: 1.9.11
python version : 3.6.8

**Comment by kyamagu** [comment]
Alright, what exactly is the expected blending? Can you upload the expected result? Note color space management is not handled in the current composite implementation.

**Comment by canghaiyunfan** [comment]
I want to get layer3's png image like this （red curve marked）
![image](https://user-images.githubusercontent.com/21115878/81522269-897b2c00-937c-11ea-813d-0d0b180150b5.png)


but get incorrectly compose result  when layer. blend_mode = BlendMode.OVERLAY
![image](https://user-images.githubusercontent.com/21115878/81522072-d3174700-937b-11ea-9f35-c2ea6a876053.png)

**Comment by kyamagu** [comment]
This seems an expected result, as Photoshop exports a similar PNG file. Layer 3 looks like this in data. I guess you are trying to mask the region of interest for the final composite image, but not exporting the layer 3.

**Comment by canghaiyunfan** [comment]
Yes, you are right. The PNG file exported form Photoshop is same as the compese result. 
But, I want to get a PNG file which only compose layer3 and layer1 corresponds to layer3  with overlay mode. How to achieve this?

Thanks.

**Comment by kyamagu** [comment]
You can use image manipulation tool like PIL to crop or mask the composite image. Optionally you can set `layer.visible = False` for unwanted layers.
