### ISSUE TITLE
Replace aggdraw with skimage.draw

### ISSUE THREAD

**Issue by FredHappyface** [psd-tools/psd-tools#222]
Hey thanks for this project!

Currently, I am making use of [an old fork](https://github.com/sfneal/psd-tools3) of this project as I had trouble installing this on a windows machine. Looks like aggdraw was causing the trouble as there are no prebuilt wheels for py3.8. Looking through the code it seems that it is only used in two places. This would leave me with two main options.

Create a more recent fork with all of the new features - though I don't particularly wish to clutter pypi.org more and would much prefer contributing back to this project (leading to option 2)

Replace aggdraw with skimage.draw as noted in one of the todos. This way I would get to contribute back.

Is this something that would be found useful?

**Comment by kyamagu** [comment]
@FredHappyface Yes, aggdraw dependency is somewhat undesirable due to the maintenance status, and it is in the todo list to remove that.

Currently the trouble is the lack of implementation of bezier curve drawing with anti-alias functionality in `skimage.draw`.

**Comment by FredHappyface** [comment]
Hmm that's a shame.

Might it be possible to supersample the curve and then resize down with the PIL antialias filter? 

I would think that 3x should be plenty

**Comment by kyamagu** [comment]
@FredHappyface For now, it is much easier to switch to Python <= 3.7 for windows platform. I imagine manual antialias incurs further overhead + quality degrade.

**Comment by FredHappyface** [comment]
Possibly, I'd certainly be interested in finding out how aggdraw goes about applying antialias.

As this is for a library, I would much prefer to support the most recent version of python as a rather large number of people use it (4th most popular for urllib3 on pypistats).

Thanks for your time 😊
