### ISSUE TITLE
'layer.composite().save' bug

### ISSUE THREAD

**Issue by wushiwein119** [psd-tools/psd-tools#225]
[test.psd.zip](https://github.com/psd-tools/psd-tools/files/4667749/test.psd.zip)
photoshop export the layer:
![image](https://user-images.githubusercontent.com/1711891/82663497-5c732700-9c62-11ea-836c-0c9bf89b223d.png)
layer.composite().save the layer:
![image](https://user-images.githubusercontent.com/1711891/82663597-89bfd500-9c62-11ea-8298-9b87686c6c87.png)
please help me.

**Comment by wushiwein119** [comment]
layer.composite(force=True) ，add force=True, then export right, why? Do you have detailed documents？

**Comment by wushiwein119** [comment]
How to synthesize multiple layers and export a picture

**Comment by wushiwein119** [comment]
any question, 
Source image：
![image](https://user-images.githubusercontent.com/1711891/82665607-bc6bcc80-9c66-11ea-92b6-39fdc071c8db.png)
export:

![image](https://user-images.githubusercontent.com/1711891/82665668-e0c7a900-9c66-11ea-8b00-f7ec02617777.png)
So many questions, please help me

**Comment by wushiwein119** [comment]
layer.composite(force=True).save , the image hasn't  drop shadow effects

**Comment by kyamagu** [comment]
@wushiwein119 Compositing is incomplete and does not support all of Photoshop's functionality
