### ISSUE TITLE
How to Add new layers in created psd files?

### ISSUE THREAD

**Issue by dhaneshwarsingh** [psd-tools/psd-tools#229]
Hi,

I wanted to create new psd file instead of editing new one. I have all the psd information stored in .JSON/SVG file, and by using those data I want to create a new psd file with the help of psd-tools. I looked into the documentation but I can not find documentation to add new layers.
I wanted to add editable layers in the psd files.

**Comment by kyamagu** [comment]
Adding a layer is not supported. [Explicitly documented here](https://psd-tools.readthedocs.io/en/latest/#features).
