### ISSUE TITLE
Can not get font size

### ISSUE THREAD

**Issue by kratosvn** [psd-tools/psd-tools#230]
Hi @kyamagu ,
I use [this document](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html?highlight=font#psd_tools.api.layers.TypeLayer) to get font data from psd. I try get font size from  styleSheet but this file don't return FontSize. Could you please help check, thank you.
[04a432d844939d0b21bb32fbff75fcf4.psd.zip](https://github.com/psd-tools/psd-tools/files/4705264/04a432d844939d0b21bb32fbff75fcf4.psd.zip)

**Comment by kyamagu** [comment]
Perhaps you can find default setting from `document_resources` or `resource_dict`?

I am not familiar with the detail of type layer styling.

**Comment by kratosvn** [comment]
thank @kyamagu for your suggestion.

**Comment by wjykim** [comment]
> thank @kyamagu for your suggestion.

Have you solved the problem?

**Comment by kratosvn** [comment]
@wjykim 
here is my way:
1. parsed = font size from engine_dict → style_run
2. yy = get yy from transform
3. font size = parsed*yy

ít work in case layer not rotate

**Comment by wjykim** [comment]
> @wjykim
> here is my way:
> 
> 1. parsed = font size from engine_dict → style_run
> 2. yy = get yy from layer transform
> 3. font size = parsed*yy
> 
> it work in case layer not rotate

It really works. Thank you~

**Comment by donghuikugou** [comment]
font_size = layer.engine_dict['StyleRun']['RunArray'][0]['StyleSheet']['StyleSheetData']['FontSize']
            print("字号：" + str(layer.engine_dict['StyleRun']['RunArray'][0]['StyleSheet']['StyleSheetData']['FontSize']))
            
            #计算字体大小
            font_size_pt = font_size * math.sqrt(layer.transform[0] * layer.transform[3] - layer.transform[1] * layer.transform[2])
            print("字号pixel：" + str(font_size_pt))
