### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kratosvn** [psd-tools/psd-tools#232]
Hi,
I try to parse this file and it spend 3 to 4G ram. 
- Enviroment: ubuntu 16 LTS
- [Uploading bfef723818b79eb5d58da2255fc7fa4e.psd.zip…](File)

Could you please help me check. Thank you

**Comment by kyamagu** [comment]
Leak or simply a lot of big layers? Opening and compositing a big PSD file consume a lot of memory in any way.

**Comment by bvb-sc** [comment]
Hi,

We are noticing a similar experience. When compositing ~600MB psd files, our RAM consumption goes up to ~20GB.
Is there a way to set a maximum amount of RAM that can be used?

Kind regards
