### ISSUE TITLE
Vivid Light not rendered correctly

### ISSUE THREAD

**Issue by bryab** [psd-tools/psd-tools#233]
Please see attached PSD.  Vivid light mode is not rendered correctly in psd_tools.  I am using the "new" composite, but I think the old one also has a (different) problem.

[psdtools_bug_vividlight.zip](https://github.com/psd-tools/psd-tools/files/4783044/psdtools_bug_vividlight.zip)

**Comment by kyamagu** [comment]
Confirmed. Currently, Hue, Color, and Vivid Light blending modes are of low quality.

**Comment by bryab** [comment]
I can give Vivid Light a try.
