### ISSUE TITLE
Is there a way to get transform of SmartobjectLayer?

### ISSUE THREAD

**Issue by youZhuang** [psd-tools/psd-tools#234]
I found the TypeLayer has transform property, Can SmartObjectLayer support this property ?

**Comment by kyamagu** [comment]
@youZhuang Check the warp attr. https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.smart_object.html#psd_tools.api.smart_object.SmartObject.warp

**Comment by youZhuang** [comment]
I rotate a smartObjectLayer, and then I print the warp property, but there is no affine transform info in this property!  

`warp {b'warpStyle': <psd_tools.psd.descriptor.Enumerated object at 0x7f9c402e0ed0>, b'warpValue': 0.0, b'warpPerspective': 0.0, b'warpPerspectiveOther': 0.0, b'warpRotate': <psd_tools.psd.descriptor.Enumerated object at 0x7f9c402e8150>, b'bounds': {b'Top ': 0.0, b'Left': 0.0, b'Btom': 243.0, b'Rght': 303.0}, b'uOrder': 4, b'vOrder': 4, b'customEnvelopeWarp': {b'meshPoints': {b'Hrzn': <psd_tools.psd.descriptor.UnitFloats object at 0x7f9c402e8450>, b'Vrtc': <psd_tools.psd.descriptor.UnitFloats object at 0x7f9c402e8490>}}}`

**Comment by kyamagu** [comment]
@youZhuang This is where Adobe does not publish the exact file format specification. All the available info are in this attribute. If you wish, you can inspect all available low-level info associated with layer in `layer._record`.

**Comment by tech-goldenphoenix** [comment]
@youZhuang Do you get rotate info from smartObjectLayer? I try with suggestion from @kyamagu but did not find out the property accordingly

**Comment by zzq0324** [comment]
> @youZhuang Do you get rotate info from smartObjectLayer? I try with suggestion from @kyamagu but did not find out the property accordingly
Have you get rotate info from smartObjectLayer? If you get, please share with me, thank you very much.
