### ISSUE TITLE
Drop Shadow is not being composed

### ISSUE THREAD

**Issue by Eatos** [psd-tools/psd-tools#235]
I have a drop shadow effect on a layer, and while exporting it, drop shadow effect is not being added to the final image that is being saved.

Python: 3.8.1
psd_tools version: 1.9.13

PSD:
https://drive.google.com/file/d/1UO6qKffcUbzoE7punqNG9GxRp0kXxDbe/view?usp=sharing

Output:
![img](https://user-images.githubusercontent.com/3318097/85309816-6d0dfb80-b4b3-11ea-8be6-14504a63e022.png)

Expected Output:
![expected](https://user-images.githubusercontent.com/3318097/85309863-80b96200-b4b3-11ea-8239-2bf77e8ffc3e.png)

**Comment by kyamagu** [comment]
Drop shadow is not supported as of the current version
https://psd-tools.readthedocs.io/en/latest/#features
