### ISSUE TITLE
Invisible channel rendered as transparency

### ISSUE THREAD

**Issue by bvb-sc** [psd-tools/psd-tools#236]
Hi,

When using the following command a channel which is marked as invisible, appears to be rendered as a transparent object. Similar results occur when using the API through python scripts, instead of the .exe directly:

`psd-tools.exe export "channel.psd" "channel.png"`

**Result**:

![image](https://user-images.githubusercontent.com/67702686/86268002-d4b8fa80-bbc7-11ea-8bfd-7c5a4117fa58.png)

**Expected result**:

![image](https://user-images.githubusercontent.com/67702686/86268021-dd113580-bbc7-11ea-9577-3c174fbb5c4e.png)

**Channel info**:

![image](https://user-images.githubusercontent.com/67702686/86268869-2746e680-bbc9-11ea-8d6e-0346f35ffd17.png)

**Reference file**:
 
[channel.zip](https://github.com/psd-tools/psd-tools/files/4859129/channel.zip)

**Version info**:
OS: Windows
Python: 3.8.3
psd-tools: 1.9.13

**Comment by kyamagu** [comment]
This extra alpha channel is saved in the `ImageData` section of PSD file, which `psd-tools` uses as a preview. There is no `visibility` field for extra alphas in PSD file. I am not sure what would be the expected handling of this.

For now, you can convert to RGB from RGBA in tools like Pillow, or use `composite` with `ignore_preview=True` option.
