### ISSUE TITLE
Can not compose with clipping layers

### ISSUE THREAD

**Issue by T7nirvana** [psd-tools/psd-tools#239]
Even though the doc said, "Compose layer and masks (mask, vector mask, and **clipping layers**)" is how compose() function works, in reality, the PIL images returned by all compose() functions of PSDImage, Group, Layers do not take **clipping layers** into account. So all the details concerning "**clipping layers**" in ".psd" file are lost when they are exported into image using psd_tools. I think it is a difference between the implementation of compose() function and its description in doc.

**Comment by kyamagu** [comment]
Use `composite` instead of deprecated `compose`

**Comment by T7nirvana** [comment]
It‘s a typo. Actually, what I have tried is exactly function composite() and then "clipping layers" are lost.

**Comment by kyamagu** [comment]
Can you upload a failing PSD example?

**Comment by T7nirvana** [comment]
Thanks a lot. Here is the PSD example:

[900x383(1).zip](https://github.com/psd-tools/psd-tools/files/4929832/900x383.1.zip)


![main logo](https://user-images.githubusercontent.com/31727994/87636820-e4157780-c773-11ea-9772-37634d6c8bda.png)
The picture above is output by applying the composite() function to the group "main logo" in the uploaded psd file. But, as you can see there are 5 clipping layers not shown in the picture
![missed clipping layers](https://user-images.githubusercontent.com/31727994/87637066-479fa500-c774-11ea-8d55-3442d4b55d08.png)

**Comment by T7nirvana** [comment]
Is there any wrong with my usage of **composite()**? Hope for guidance eagerly.

**Comment by kyamagu** [comment]
Can you check with the latest version 1.9.14?

**Comment by kyamagu** [comment]
Compositing is still experimental. Expect bugs

**Comment by T7nirvana** [comment]
> Can you check with the latest version 1.9.14?

Awesome! The problem with clipping layers is fixed.

> Compositing is still experimental. Expect bugs

 I will take care when using the function and really appreciate your active maintenance and exploratory work. Thanks again.

**Comment by kyamagu** [comment]
Ok, the bug is identified & is still present in v1.9.14. Will be fixed in the next release
