### ISSUE TITLE
Creating a PSD file from a numpy array.

### ISSUE THREAD

**Issue by ysig** [psd-tools/psd-tools#248]
I am trying to use your library for something really simple:

I have a numpy array with 3 RGB chanels and two alpha channels.
I want to convert it to a psd file, so I can later apply transformations in photoshop on the annotated alpha layers.

I guess it a very simple task but I haven't find any way to do it by having a look in the documentation.
I guess it should be something in the lines of the following:

```
>> im.shape
(.., .., 4)

psd = PSD()
psd.add_layers_from_numpy(im, names=["R", "G", "B", "alpha-1", "alpha-2"])
with open(of, 'wb') as f:
    psd.write(f)

``` 

Can you instruct me how to do this?
Thanks in advance.

**Comment by kyamagu** [comment]
Editing of layer structure, such as adding or removing a layer, is not supported. See [feature list](https://psd-tools.readthedocs.io/en/latest/#features)

For that workload, I would recommend exporting PNG or JPEG then open that file in Photoshop.
