### ISSUE TITLE
Can't get decompressed data from PSB file

### ISSUE THREAD

**Issue by albertovitto** [psd-tools/psd-tools#251]
**Describe the bug**
Hi,
I have a simple 1500x1000 RGB image in .psb format but I can't manage to get the list of bytes corresponding to each channel. There are no problems with the same image saved in .psd format.

```python
psd_file = PSDImage.open("blue.psb")
header = FileHeader(channels=3, height=1000, width=1500, depth=8, color_mode=ColorMode.RGB)
data = psd_file._record.image_data.get_data(header=header)
```

```python
Traceback (most recent call last):
  File "C:\Users\alber\anaconda3\envs\env\lib\site-packages\psd_tools\compression\__init__.py", line 95, in decode_rle
    rle_impl.decode(fp.read(count), row_size) for count in bytes_counts
  File "C:\Users\alber\anaconda3\envs\env\lib\site-packages\psd_tools\compression\__init__.py", line 95, in <genexpr>
    rle_impl.decode(fp.read(count), row_size) for count in bytes_counts
  File "src\psd_tools\compression\_rle.pyx", line 40, in psd_tools.compression._rle.decode
ValueError: Expected 1500 bytes but decoded only 0 bytes
```

**Expected behavior**
Get a list with bytes from R, G and B channel.

**File and screenshots**
[psd psb image.zip](https://github.com/psd-tools/psd-tools/files/5523730/psd.psb.image.zip)

**Environment**
 - platform : win-64
 - conda version [4.8.2]
 - Python [3.7.9]
 - Version [v1.9.16]

Thank you.

**Comment by kyamagu** [comment]
because you are using PSD header, not PSB header (version must be 2)

```python
psb = PSDImage.open("blue.psb")
data = psb._record.image_data.get_data(header=psb._record.header)
```

I would recommend using high-level API instead of private methods.

```python
array = psb.numpy()
```

**Comment by albertovitto** [comment]
Thank you very much @kyamagu !
