### ISSUE TITLE
shape layer returning as solidcolorfill

### ISSUE THREAD

**Issue by grumpygamer** [psd-tools/psd-tools#254]
I just upgraded from version 1.9.8 to 1.9.16 (and to python3.9.1).

In my PS file I have both "shape" and "solidcolorfill" layers.  Under 1.9.16 my "shape" layers are returning "solidcolorfill" and the bbox is off (as well as child.width and child.height).  In PS size of the shape is (190,299,340,349) and the bbox is (189, 297, 341, 450).  If I rasterize it to pixels, then a "pixel" type is returned and the bbox is correct.

Did something change?

**Comment by kyamagu** [comment]
It is best to upload a failing example here

**Comment by grumpygamer** [comment]
The two layers named @bounds should return the same bounds.  The @bounds layer in the test1 group is a "shape" but it's returned as a "solidcolorfill".  This seems to have changed in 1.9.16 as everything worked correctly in 1.9.8.

https://www.dropbox.com/s/fdxsapenrpeta1w/BoundsTest.psd?dl=0

**Comment by grumpygamer** [comment]
What is the process of this changed being put in what is downloaded via pip?  I have several team members that need this fix and hand distributing the change is difficult for non-tech users.

**Comment by kyamagu** [comment]
The fix is as simple as:

    pip install --upgrade psd-tools

For the detail of what's changed, refer https://github.com/psd-tools/psd-tools/pull/255/commits/caee5604b81077d3532695c980f464f338eff2a8

**Comment by grumpygamer** [comment]
I already did that. I still see 1.9.16, which is which I was asking.

**Comment by kyamagu** [comment]
Ok, forgetting to set up release CI, now fixed--
山口光太
（株）サイバーエージェント AI Lab
050-5305-9404
yamaguchi_kota@cyberagent.co.jp
