### ISSUE TITLE
Update thumbnail after change some layer visibility

### ISSUE THREAD

**Issue by jindili** [psd-tools/psd-tools#258]
Simple Code to hide some guide and mask layers in psd files and save, working super fast even with large psd files.

```python
for layer in psd:
    if layer.name in ["mask", "guide"]:
        layer.visible = False
```

The file it self is right when open it in Photoshop, But it still use the old embedded thumbnail,
I want to know if there is a way to update the embedded thumbnail.

**Comment by kyamagu** [comment]
No, there is no way to update a rendered thumbnail. There is no full-featured rendering engine built in psd-tools.

**Comment by jindili** [comment]
Is there some alternate way to render the image external or just use another image to replace the embedded one ?

**Comment by kyamagu** [comment]
Use Adobe Photoshop for that workload.
