### ISSUE TITLE
How is the data stored in memory?

### ISSUE THREAD

**Issue by vertgo** [psd-tools/psd-tools#262]
Like the several other issues asking for write, I am hoping to do a simpler write process where I can digitize a numpy array of a PIL image of the same shape (dimensions and channels) and substitute it for a layer, while preserving the mask information and any effects (no need to write that), and then call composite on it. Where in the code does that data get decoded, I can try to make the change and a pull request.

@kyamagu?

**Comment by kyamagu** [comment]
See [composite implementation](https://github.com/psd-tools/psd-tools/blob/master/src/psd_tools/composite/__init__.py#L63).
