### ISSUE TITLE
How to get which font file is used in the type layer?

### ISSUE THREAD

**Issue by zhenzi0322** [psd-tools/psd-tools#265]
I'm using psd-tools and I don't know how to get the font information of layer.kind=='type' layer.

**Comment by zhenzi0322** [comment]
How do I get the detailed path to the font. At the moment I know that SimHei is a black font, but I only find the black font in my local disk, but I can't find the information of the font named SimHei.

**Comment by kyamagu** [comment]
Only the file creator knows where the font exists. I do not know how Adobe Photoshop handles fonts. PSD files only records the font name that might not exist in your environment.
