### ISSUE TITLE
Unknown tagged block b'vowv'

### ISSUE THREAD

**Issue by aojdavis** [psd-tools/psd-tools#269]
I've been getting this warning and saw back in issue [#63 ](https://github.com/psd-tools/psd-tools/issues/63) that a similar warning was fixed by adding the key and parsing function to constants.py and layer_effects.py. What I'm curious about is how to find the formatting of the undocumented tagged block and how to compare it to the others so that I can determine if that is going to be a viable approach to solve this issue.

**Comment by kyamagu** [comment]
Adobe periodically adds new features and we expect to see this type of unknown data structure whenever there is updates to Photoshop. It seems recent undocumented structures tend to have what is called `Descriptor` structure in the tagged block section, which is implemented [here](https://github.com/psd-tools/psd-tools/blob/master/src/psd_tools/psd/descriptor.py#L736). When I see unknown tagged block, the first thing I do is to check if the binary is parsable by the descriptor format.

**Comment by aojdavis** [comment]
@kyamagu Thanks, for the quick response. I tried out both DescriptorBlock and DescriptorBlock2 but both resulted in assertion errors. DescriptorBlock resulted in `AssertionError: read=0, expected=4` and DescriptorBlock2 resulted in `AssertionError: read=4, expected=8` I then tried EmptyElement and was able to parse the .psd file with no warnings or errors, and the output was as expected. Though I have a feeling that EmptyElement isn't the right format to parse the binary and this is really just a bandaid fix to get the warnings to go away... That's just a hunch though as I am still very new to python.

**Comment by kyamagu** [comment]
Okay, if that doesn't work, you need to look at the binary sequence and guess what format it is.

In any case, the unknown tags do not do any harm and can be safely ignored

**Comment by velyan** [comment]
You're probably already aware of this, but this warning seems to be happening with any file created with the latest PSD version (23.3.1) 
```
/usr/local/lib/python3.9/site-packages/psd_tools/psd/tagged_blocks.py:249: UserWarning: Unknown key: b'vowv'
  warn(message)
Unknown key: b'vowv'
/usr/local/lib/python3.9/site-packages/psd_tools/psd/tagged_blocks.py:266: UserWarning: Unknown tagged block: b'vowv', b'\x00\x00\x00\x02'
  warn(message)
Unknown tagged block: b'vowv', b'\x00\x00\x00\x02'
```

**Comment by kyamagu** [comment]
I don't have any example file that has `vowv` key built from photoshop 23.3.1.

Ignore the warning if that doesn't do any harm.

**Comment by velyan** [comment]
Here's an example file: 
[test.psd.zip](https://github.com/psd-tools/psd-tools/files/8560246/test.psd.zip)

**Comment by kyamagu** [comment]
@velyan Thanks, it seems the field has 4 bytes and is related to vector shape. But that's all my guess and cannot tell what this indicates. Will add an update to suppress this warning.

**Comment by velyan** [comment]
Thanks for fixing!

**Comment by velyan** [comment]
Thanks for fixing!

> and is related to vector shape
How did you know it's related to vector shape?

**Comment by kyamagu** [comment]
@velyan Yes, the `vo` prefix
