### ISSUE TITLE
text layer runlength error

### ISSUE THREAD

**Issue by MisterChing** [psd-tools/psd-tools#277]
when i have a text layer, the content is  "abcd".
why engine_dict['StyleRun']['RunLengthArray']  == 2
using demo code 
`fontset = layer_obj.resource_dict['FontSet']
        runlength = layer_obj.engine_dict['StyleRun']['RunLengthArray']
        rundata = layer_obj.engine_dict['StyleRun']['RunArray']
        print(runlength.__dict__)
        index = 0
        for length, style in zip(runlength, rundata):
            substring = text[index:index + length]
            stylesheet = style['StyleSheet']['StyleSheetData']
            font = fontset[stylesheet['Font']]
            print('%r gets %s' % (substring, font))
            index += length`

result like:
`'a' gets {'Name': 'AdobeHeitiStd-Regular', 'Script': 3, 'FontType': 2, 'Synthetic': 0}
'bcd\r' gets {'Name': 'AdobeHeitiStd-Regular', 'Script': 3, 'FontType': 2, 'Synthetic': 0}`
but  "a" and "bcd" should be together

**Comment by kyamagu** [comment]
The result is what the PSD file internally saves. psd-tools cannot do anything about that

**Comment by MisterChing** [comment]
> The result is what the PSD file internally saves. psd-tools cannot do anything about that

yes，i found some case is right，maybe it is the way i typed affects。thx for reply。
