### ISSUE TITLE
text layer line-height text-color

### ISSUE THREAD

**Issue by MisterChing** [psd-tools/psd-tools#278]
how to get some text properties like line-height text-color  relative to css value

1. as i know  'line-height' in ps and css is different。maybe "line-height" == "line-height-ps" - "word-height"
but where to get a "word-height" in psd-tools

2. how to get a rgb color from `'FillColor': {
					'Type': 1,
					'Values': [1.0, 0.20001, 0.20001, 0.20001]
				},`

3. is every number/float value in engine_dict should multiply layer.transform[3] like font_size ? 

@kyamagu thx very much

**Comment by kyamagu** [comment]
I cannot answer any specific question on details like this, as there is no official specification. You can only try and see if the value is desired one

**Comment by MisterChing** [comment]
> I cannot answer any specific question on details like this, as there is no official specification. You can only try and see if the value is desired one

ok...
