### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [psd-tools/psd-tools#279]
Problem
---------
On aarch64, ‘pip install psd-tools’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPi.

Resolution
-----------
On aarch64, ‘pip install psd-tools’ should download the wheels from PyPi

@kyamagu, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by odidev** [comment]
PR raised for reviewing.

**Comment by kyamagu** [comment]
Thanks!
