### ISSUE TITLE
Embed in py2exe

### ISSUE THREAD

**Issue by Frulko** [psd-tools/psd-tools#28]
Hi, 
i just discover your lib for manage psd files.
I want to make a standalone app who convert psd in a simple png.
But when I use py2exe and after i launch the build exe, i have some errors :+1: 

```
Traceback (most recent call last):
  File "psd_process.py", line 5, in <module>
  File "psd_tools\__init__.pyc", line 2, in <module>
  File "psd_tools\user_api\__init__.pyc", line 4, in <module>
  File "psd_tools\user_api\psd_image.pyc", line 12, in <module>
  File "psd_tools\user_api\pil_support.pyc", line 7, in <module>
  File "psd_tools\icc_profiles.pyc", line 9, in <module>
  File "PIL\ImageCms.pyc", line 156, in __init__
IOError: cannot open profile file
```

my script is very simple : 

``` python
#!/usr/bin/python 

import sys

from psd_tools import PSDImage


psd = PSDImage.load(sys.argv[1])
merged_image = psd.as_PIL()
merged_image.save(sys.argv[1]+'.png')
print "Success Export"

```

Have you any idea for solve this problem ?

Thanks a lot !

**Comment by mmagician** [comment]
Hi @Frulko,

I was trying to do a vary similar thing (in fact, the goal was the same) and encountered the exact same error as you described here. Please let me know if you've managed to solve it!

Many thanks :)

**Comment by bazilm** [comment]
I solved it by adding a copy of psd_tools to project directory and modifying the icc_profiles.py line 5 to

    GRAY_PATH = os.path.join(os.path.dirname(__file__),os.pardir,os.pardir,'icc_profiles', 'Gray-CIE_L.icc')

and adding  the icc_profiles folder   to dist folder.

**Comment by xboomx** [comment]
I'm using Pyinstaller and I had to add folder: psd_tools\icc_profiles\ to my app. I did this in app.spec file to attach this everytime I execute building app (pyinstaller app.spec command - not app.py).

a = Analysis(...
             datas=[('C:\\Python27\\Lib\\site-packages\\psd_tools\\icc_profiles\\*.*', 'psd_tools\\icc_profiles' )],
...
)

**Comment by deo85** [comment]
I am having this same issue with py2app has any one found a solution for this? How do I know the relative path that PIL his looking for?
