### ISSUE TITLE
Text alignment missing

### ISSUE THREAD

**Issue by FlowerHuaer** [psd-tools/psd-tools#281]
No text alignment is found in the document. How do you correspond to the text layer?

**Comment by kyamagu** [comment]
There is no official specification on the text formatting structure.
You can inspect the content of [engine data](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.psd.engine_data.html) if there exists any relevant field

**Comment by FlowerHuaer** [comment]
![image](https://user-images.githubusercontent.com/30189606/130056442-d7f289f0-7330-42cd-af73-b7d2b4dfc9a4.png)


OK, there is no corresponding alignment in the document. I need such a style, such as align: Center. Is there a solution?

In addition, do you have corresponding parameters for the writing mode and direction of the text? See the picture for details

@kyamagu

**Comment by kyamagu** [comment]
I do not know the internal specification of engine_dict, and cannot answer. You can always `print` or `pprint` low level data structure. Also see [TypeLayer doc](https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.layers.html#typelayer) and its implementation

**Comment by FlowerHuaer** [comment]
After repeated inquiry, I finally found the answer in the "justification" parameter. Please leave the answer to others here!!

**Comment by FlowerHuaer** [comment]
After repeated inquiry, I finally found the answer in the "justification" parameter. Please leave the answer to others here!!

The corresponding values are:

```python
#layer.engine_dict['ParagraphRun']['RunArray'][0]['ParagraphSheet']['Properties']['Justification']
def getAlign(self,num):
    enum = [(0,'left'),(2,'center'),(1,'right'),(3,'start'),(5,'center'),(4,'end'),(6,'justify')]
    for item in enum:
      n,text = item
      if num == n:
        return text
    return 'left';
```

**Comment by kyamagu** [comment]
Sounds good
