### ISSUE TITLE
Citation for research paper

### ISSUE THREAD

**Issue by StefanBaar** [psd-tools/psd-tools#282]
I would like to cite psd-tools in a research paper. Is there a .bib file? something like:

@Misc{psd-tools
  author =   {Kota Yamaguchi and Mikhail Korobov and others},
  title =     {{psd-tools}: Open source psd tools for {Python}},
  year =      {2019--},
  url = "https://psd-tools.readthedocs.io"
}

**Comment by kyamagu** [comment]
You can use whatever format to cite. Perhaps authors should be 'psd-tools developers' or entirely omitted, because there are many contributors

**Comment by StefanBaar** [comment]
Thank you for the quick response. 
Will do
