### ISSUE TITLE
psd_tools.api.adjustments.HueSaturation example

### ISSUE THREAD

**Issue by johnou** [psd-tools/psd-tools#289]
Hi @kyamagu!

I've been looking at the documentation, examples and test code for psd-tools but haven't found any way to add / apply HueSaturation to one or more PixelLayer layers, is this supported?

Thanks for your time,

J

**Comment by kyamagu** [comment]
Editing layers is not supported, as explicitly stated in the [documentation](https://psd-tools.readthedocs.io/en/latest/#features)
