### ISSUE TITLE
can text layer be modified?

### ISSUE THREAD

**Issue by dmbraunst** [psd-tools/psd-tools#292]
Hi,
Great repo for operating directly on PSD files.
Is it possible with psd-tools to modify the text in a PSD text layer?
I did not see documentation to support this operation.

Thanks.

**Comment by kyamagu** [comment]
[See the docs](https://psd-tools.readthedocs.io/en/latest/)

> Not supported:
> 
> Editing of layer structure, such as adding or removing a layer
> Composition of adjustment layers
> Composition of many layer effects
> Font rendering
