### ISSUE TITLE
Question: can not get layer from psd, which has only one layer?

### ISSUE THREAD

**Issue by lookslikeadog** [psd-tools/psd-tools#305]
I want to get layer from psd file using python 3.9 and psd-tools 1.9.19, but output nothing.
from psd-tools import PSDImage
psd = PSDImage.open(file_path)
for layer in psd:
    print(layer)

**Comment by kyamagu** [comment]
It's possible that the PSD file does not contain a layer.

**Comment by lookslikeadog** [comment]
> 
but when i open it in photoshop, a background layer can show in the layer bar

**Comment by kyamagu** [comment]
@lookslikeadog That is absolutely possible, because Photoshop shows a layer-less PSD file (simple raster image) as if there is just one layer.
