### ISSUE TITLE
Text layer read as pixel

### ISSUE THREAD

**Issue by esnosy** [psd-tools/psd-tools#338]
I try to load this PSD file the text layer "foobar" is loaded as a pixel layer :/,
this warning shows in terminal:
```
Divider SectionDivider.OTHER found.
Divider SectionDivider.OTHER found.
```

note that the foobar text was created using Photopea while the other text layers that work load correctly as text layers,
[placeholders-with-frames_ungrouped.zip](https://github.com/psd-tools/psd-tools/files/9844202/placeholders-with-frames_ungrouped.zip)

might be related: https://github.com/psd-tools/psd-tools/issues/337

**Comment by dario-spagnolo** [comment]
I confirm this bug and submitted a PR.

It also fixes layer categorization for type layers incorrectly treated as pixel layers and produced by Photoshop. For copyright reasons I cannot share the PSD.
