### ISSUE TITLE
Retention of vector data?

### ISSUE THREAD

**Issue by ylluminate** [psd-tools/psd-tools#35]
Does `psd-tools` retain vector data such that it will import shapes as vectors?  I have been talking to the [Sketch](http://bohemiancoding.com/sketch/) team about adding support for importation of PSDs into their app, however so far I have not found any options that will do the trick for them because they will not move forward with this functionality until PSD importation can retain vector data for shapes, etc.

**Comment by kyamagu** [comment]
Vector is accessible in ver 1.8.8
https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.shape.html#psd_tools.api.shape.VectorMask.paths
