### ISSUE TITLE
PSD is showing black pixels insted of transparent when using coverting from pil

### ISSUE THREAD

**Issue by BishrGhalil** [psd-tools/psd-tools#356]
**Describe the bug**
I have PNGs that I converted to pillow `Image` objects and modified those images, they are in RGBA mode and when I save them the transparency work, However when I convert them to `PSDImage` objects using `frompil` method, I get black pixels instead of transparent pixels, even-though it has the alpha channel in Photoshop.  

**To Reproduce**
```python
img = PIL.Image.open("my_transparent_img.png")
img = img.convert("RGBA")
# Some image processing...
psd = PSDImage.frompil(img)
psd.save("my_transparent_psd.psd")
```

**Expected behavior**
I want to convert a transparent image to a PSD file and still have transparent pixels in Photoshop, Or to be able to make a layer mask from the alpha channel.

**File and screenshots**
PSB FILE:
https://drive.google.com/file/d/1mg5geT_xUJwG4TlUV0QHauVNvOaEKA9b/view?usp=share_link

Screenshots
inside of Photoshop:
![screen](https://github.com/psd-tools/psd-tools/assets/75081255/76ba2a91-8216-42ce-8628-fa91aeacfc29)

when saving with pillow as PNG:
![03](https://github.com/psd-tools/psd-tools/assets/75081255/2e6ce407-a3a7-4001-943b-4741f2db2ffe)

**Environment**
 - Python [3.10]
 - Version [v1.9.15]

**Comment by danielcapturely** [comment]
Hey @BishrGhalil, did you ever figure this out? I am having similar issues but haven't figured out what I should be doing.
