### ISSUE TITLE
how can i get textbox information from psdtools?

### ISSUE THREAD

**Issue by Source-Code-Sivir** [psd-tools/psd-tools#357]
![image](https://github.com/psd-tools/psd-tools/assets/50519354/9e8cc1ed-2996-44ce-9493-cc5f99de4eda)
there is a textbox in the pic, how can i get the textbox info from psd-tools? it seems that only  exact text bbox info now..

**Comment by razertory** [comment]
Same issue.

**Comment by razertory** [comment]
It seems like ` box_bounds = layer.engine_dict['Rendered']['Shapes']['Children'][0]['Cookie']['Photoshop'].get('BoxBounds', None)` then you will finally get a box like structure 
`[0,0,x,y]`

**Comment by Source-Code-Sivir** [comment]
> It seems like ` box_bounds = layer.engine_dict['Rendered']['Shapes']['Children'][0]['Cookie']['Photoshop'].get('BoxBounds', None)` then you will finally get a box like structure `[0,0,x,y]`

thx, I  will try it

**Comment by abdulhafeez1724** [comment]
not working there is no ['Cookie'] in overall docs
