### ISSUE TITLE
Merged preview image has transparency when it shouldn't

### ISSUE THREAD

**Issue by floogulinc** [psd-tools/psd-tools#369]
A PSD file may contain any number of channels up to 56. After the main color channels (eg 3 for RGB) the next channel may be alpha transparency or it may be a mask channel. It seems psd-tools sometimes identifies when this is the case using Alpha Identifiers or maybe something else but depending on what exported the file this isn't always available. The most reliable way to identify whether the merged preview image has an alpha transparency channel is using the sign of the layer count as indicated in the PSD spec below. This seems to currently be ignored and sometimes produces incorrect merged image results when the image has no transparent alpha channel but one or more alpha channels that are used for masks because one of the mask channels is used as transparency usually leading to parts of the image being fully transparent that shouldn't be.

In the PSD spec, (https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_16000):
> Layer count. If it is a negative number, its absolute value is the number of layers and the first alpha channel contains the transparency data for the merged result.

The layer count being positive indicates the merged image doesn't contain an alpha channel, even if there are additional channels present.

A quick fix I was able to implement is adding a couple lines to `has_transparency` in `numpy_io.py` to check for this condition:

```diff
def has_transparency(psd):
    keys = (
        Tag.SAVING_MERGED_TRANSPARENCY,
        Tag.SAVING_MERGED_TRANSPARENCY16,
        Tag.SAVING_MERGED_TRANSPARENCY32,
    )
    if psd.tagged_blocks and any(key in psd.tagged_blocks for key in keys):
        return True
    if psd.channels > EXPECTED_CHANNELS.get(psd.color_mode):
        alpha_ids = psd.image_resources.get_data(Resource.ALPHA_IDENTIFIERS)
        if alpha_ids and all(x > 0 for x in alpha_ids):
            return False
+       if(psd._record.layer_and_mask_information.layer_info is not None and psd._record.layer_and_mask_information.layer_info.layer_count > 0):
+           return False
        return True
    return False
 ```

**Comment by kyamagu** [comment]
@floogulinc Ok, can you make a PR?

**Comment by floogulinc** [comment]
Yeah, I'm not too familiar with the codebase yet so I'm not sure if this is exactly the right way to do it but I'll make a PR.
