### ISSUE TITLE
mask support on layers and groups

### ISSUE THREAD

**Issue by Soviut** [psd-tools/psd-tools#40]
It would be really useful if the `Layer` and `Group` objects could list any masks they might have attached to them. I was hoping to be able to get the bounding boxes for masks I have in a document.

**Comment by kmike** [comment]
Hi @Soviut,

Agreed, that'd be a nice addition to user_api.

Currently I don't have time to add new features to the library myself, but I can answer questions and review a pull request. Most changes since v0.9.1 (and maybe earlier) were from other contributors; it goes well :)

**Comment by Soviut** [comment]
I'd gladly add a pull request if I knew what to look for in the raw data.

**Comment by Soviut** [comment]
I was able to find the mask data in `layer._info.mask_data` which has `top`, `left`, `bottom` and `right` bounds. So I was able to do the following for now:
```python
from psd_tools.user_api.psd_image import BBox

if layer._info.mask_data:
    mask_bounds = BBox(
        layer._info.mask_data.top, 
        layer._info.mask_data.left, 
        layer._info.mask_data.bottom, 
        layer._info.mask_data.right
    )
```

**Comment by kmike** [comment]
Looks good. How do you feel about adding it to https://github.com/kmike/psd-tools/blob/master/src/psd_tools/user_api/psd_image.py (as a Layer attribute?) and documenting in README?

**Comment by Soviut** [comment]
I think I might be able to do that in the near future.

**Comment by kmike** [comment]
Great, thanks!

**Comment by aubanel** [comment]
Interesting piece of information. However I would be interested to know how to extract the mask data as a PIL, in order for me to export two pngs or to apply the mask in pillow to produce just one png, something like :
```python

from PIL import Image, ImageOps

mask = Image.open('mask.png').convert('L')
im = Image.open('image.png')
output = ImageOps.fit(im, mask.size, centering=(0.5, 0.5))
output.putalpha(mask)
output.save('output.png')

```

Any idea where to look for it ?

**Comment by kmike** [comment]
@aubanel layer and mask data specs are here: http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1031423. Data structures psd-tools produce should match the format in specs; there is `psd_image.decoded_data.layer_and_mask_data` field. It must be possible to extract necessary information from there, but I haven't checked the details.
