### ISSUE TITLE
Multiple unknown warnings.

### ISSUE THREAD

**Issue by fabiocaccamo** [psd-tools/psd-tools#415]
**Describe the bug**
I'm getting many warnings like these:
```python
Unknown image resource 1092
Unknown key: b'CAI '
Unknown tagged block: b'CAI ', b'\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x00 ... =77'
Unknown key: b'OCIO'
Unknown tagged block: b'OCIO', b'\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x00\x00\x1bdo ... =170'
Unknown key: b'GenI'
Unknown tagged block: b'GenI', b'\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x00\x00\x0bge ... =55'
```

**To Reproduce**
Unfortunately I can't attach the .psd file, btw it's quite simple, there is a base layer with a .jpg image and some correction layers on top of it (see screenshot below).

**Expected behavior**
No warnings.

**File and screenshots**
<img width="273" alt="Screenshot 2024-06-16 at 16 27 34" src="https://github.com/psd-tools/psd-tools/assets/1035294/967fa38a-ebb2-430e-888f-0c09610c1a10">

**Environment**
 - Python `3.8.8`
 - Version `1.9.33`

**Comment by kyamagu** [comment]
These seem like new resources introduced in the recent versions of Photoshop, but they are not documented anywhere.
https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/

psd-tools cannot parse those unknown binaries and hence show warning messages. You can safely ignore these.

**Comment by fabiocaccamo** [comment]
@kyamagu thank you!
