### ISSUE TITLE
PixelLayer conversion when the pixel layer is empty

### ISSUE THREAD

**Issue by al3ks1s** [psd-tools/psd-tools#433]
Hi, 

When going through a script for fusing psds, i encountered a bug concerning the pixel layer conversion.

Basically, when calling self.topil() in _convert, an entirely empty pixel layer with no data will send back a `None` object. Causing the conversion to a new color mode to fail in PixelLayer.frompil.

Do you think the topil() in the conversion should be changed to composite() (as composite returns a proper pil object) or modify topil to send back an empty image?

**Comment by kyamagu** [comment]
`topil` is intended for exporting the raw pixel data, and if there is no real channel data in the layer, it returns `None`. If you need to ensure the output is always an image object, yes, you should use `composite`.

**Comment by al3ks1s** [comment]
I will just add a check in the conversion function that will handle this special case.
Along a few minor changes that I thought of afterward
