### ISSUE TITLE
PixelLayer.frompil Displays Black Color for Transparent Parts of the Image

### ISSUE THREAD

**Issue by aln-mcw** [psd-tools/psd-tools#441]
**Describe the bug**
As title. The transparent part of the image turned black by using PixelLayer.frompil

**To Reproduce**

```python

... Previous image processing

# Convert output image into a PIL Image object
image_stream = io.BytesIO(output_image)
image1 = Image.open(image_stream)
image1 = image1.convert('RGBA')  # image1 has transparent bg if I save it as PNG file
layer1 = PixelLayer.frompil(image1, psd, "Layer 1", top=0, left=0, compression=Compression.RAW)

# Load the second image
image2 = Image.open("new_bg.jpg")
layer2 = PixelLayer.frompil(image2, psd, "Layer 2", top=0, left=0, compression=Compression.RAW)
psd.append(layer2)
psd.append(layer1)

# Save PSD file
psd.save("output.psd")

```

**Expected behavior**
The top layer remain its transparent background

**File and screenshots**
<img width="862" alt="Screenshot 2024-10-11 at 14 39 54" src="https://github.com/user-attachments/assets/4a9b0593-87ce-4d98-ab3c-a78537b7ced9">

**Environment**
 - Python [3.11.7]
 - Version [v1.10.1]

**Comment by al3ks1s** [comment]
Your PSD is most likely in RGB mode and not RGBA, PixelLayer.frompil will convert any image given to it into the Color mode the PSD has.

**Comment by aln-mcw** [comment]
Thank you, solved after changing from 
`psd = PSDImage.new(mode="RGB", size=(width, height))`
to 
`psd = PSDImage.new(mode="RGBA", size=(width, height))`
