### ISSUE TITLE
Color desaturation when exporting PSD to JPG compared to Photoshop.

### ISSUE THREAD

**Issue by fabiocaccamo** [psd-tools/psd-tools#445]
**Describe the bug**
Exporting some `.psd` files to `.jpg`, the colors are visibly different (they appear desaturated, especially reds) compared to when I export the same files using Photoshop.

**To Reproduce**

- Export a psd to jpg using `psd-tools`:
```python
psd = PSDImage.open('snake.psd')
img = psd.composite()
img.save('snake.jpg', "JPEG", quality=100, dpi=(300, 300))
img.close()
```

- Export the same psd file to jpg using Photoshop

- Compare the two jpg images

**Expected behavior**
The two images colors should match.

**File and screenshots**
I attach also a `.zip` file containing the `.psd` and the two different exported `.jpg` files: [snake.zip](https://github.com/user-attachments/files/17436005/snake.zip)

![snake-export-using-photoshop](https://github.com/user-attachments/assets/a7c7eb8a-1a80-459f-b184-67574d7cb719)

![snake-export-using-psdtools](https://github.com/user-attachments/assets/1927aabb-cdc9-4167-85a2-4200e1e5aa02)

**Environment**
 - `Python 3.12`
 - `pillow==10.4.0`
 - `psd-tools==1.10.1`

**Additional context**

- In the `.psd` I attached there are many regulation-layers, but even merging all layers in a single layer the problem persists, so the cause are not the regulation-layers.

- I tried also to save the image also as `.png`, but the problem persists, so I would exclude that it's a `pillow` issue.

---

✨ Thank you very much for this great library!

**Comment by kyamagu** [comment]
There could be multiple possibilities. Check the color mode of the PSD file first. If that is not RGB, the result probably won't be the same

**Comment by fabiocaccamo** [comment]
@kyamagu the color mode of the PSD is RGB (8 Bit / Channel)

**Comment by EmilDohne** [comment]
@fabiocaccamo This is because the image data is stored without the ICC Profile (color management) applied, this is done live by photoshop. Thankfully `psd-tools` exposes ways to apply this like so:

```py
from psd_tools import PSDImage

psd = PSDImage.open('snake.psd')
img = psd.composite(apply_icc=True)
img.save('snake.jpg', "JPEG", quality=100, dpi=(300, 300))
img.close()
```

The exported image then looks like this:
![snake](https://github.com/user-attachments/assets/1bbf3253-a8f3-4c77-a1cd-153d73301eea)


@kyamagu I think it may actually be worthwhile making this on by default since I cant think of many use cases where you don't want the ICC profile to be applied

**Comment by fabiocaccamo** [comment]
@EmilDohne I confirm that this solved the problem, thank you very much!
I agree that `apply_icc=True` should be the default.

**Comment by fabiocaccamo** [comment]
@kyamagu @EmilDohne since this issue has been resolved, I close this issue.

Feel free to open a new issue for the `apply_icc=True` default.
