### ISSUE TITLE
Warnings on .psd open : `Unknown image resource 1092`

### ISSUE THREAD

**Issue by mrlinds** [psd-tools/psd-tools#454]
**Describe the bug**
on opening psd file I get the following warnings.
```
Unknown image resource 1092
Unknown key: b'CAI '
Unknown tagged block: b'CAI ', b'\x00\x00\x00\x03\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x00 ... =77'
Unknown key: b'GenI'
Unknown tagged block: b'GenI', b'\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x00\x00\x0bge ... =55'
```

**To Reproduce**

```python
psd = PSDImage.open('light_bloom_fx.psd')
```

**Expected behavior**
I'd like to not have these warnings, or at least an option to suppress them as it creates distracting noise in a log where I'm trying to get artists to pay attention to output.

**File and screenshots**
[light_bloom_fx.zip](https://github.com/user-attachments/files/18100538/light_bloom_fx.zip)

**Environment**
 - Python [3.12]
 - Version [v1.10.0]

**Additional context**
Issue has existed for several versions, and is not something newly introduced

**Comment by kyamagu** [comment]
Set the environment variable and logging module.

```bash
export PYTHONWARNINGS=ignore
```

```python
import logging
logging.getLogger("psd_tools").setLevel(logging.CRITICAL)
```
