### ISSUE TITLE
Error parsing layer: invalid signature ('\xc7%\xc0\xc7')

### ISSUE THREAD

**Issue by mociepka** [psd-tools/psd-tools#46]
Unfortunately I can't upload the PSD file I hope only error will help.

**Comment by kmike** [comment]
Hi @mociepka,

I can do nothing without an example. Thanks for the bug report though - it is good to know the problem exists.

**Comment by mociepka** [comment]
I will try remove content from file and maybe without it error will occur again.

**Comment by kmike** [comment]
Thanks! A file without image content is even better (because it will be smaller in size), especially if you're OK with adding it to the testing suite.

**Comment by fabiocaccamo** [comment]
I used psd-tools to convert more than 100 psd(s) to jpg, I succesfully converted most of them, but I got some errors too:

- Error parsing layer: invalid signature ('XWVV')
- Error parsing layer: invalid signature ('MS]a')
- Error parsing layer: invalid signature ('*+34')
- Error parsing layer: invalid signature ('pjch')
- Error parsing layer: invalid signature ('\x8d\x8e\xfe\x8c')
- Error parsing layer: invalid signature ('\x93\x90\x90\x93')
- Error parsing layer: invalid signature ('\xb2\xb4\xb2\xab')
- Error parsing layer: invalid signature ('\x91\xfd\x92\x08')

Unfortunately I can't upload any of the psd(s)

**Comment by PiOverFour** [comment]
I seem to be having a similar issue. The file was created in Krita 3.0. The error is the following:
`psd_tools.exceptions.Error: Error parsing layer: invalid signature (b'\x00\x1a\x00\x1a')`
It seems to happen in a layer hierarchy where is a single group is on the top level.
[test_points.psd.zip](https://github.com/psd-tools/psd-tools/files/289315/test_points.psd.zip)

Could we maybe have a flag to log layer errors but continue anyway, instead of raising?

**Comment by deanblacc** [comment]
Was there any proposed solution to this ? Im running into the exact same issue for some psd files but cant work out what causes it or how to mitigate it.

**Comment by fabiocaccamo** [comment]
@deanblacc can you provide your .psd(s) for testing?

**Comment by deanblacc** [comment]
@fabiocaccamo I downloaded it from here https://assets.adobe.com/link/60584eba-a002-4c8e-45f8-aa465b46aa1d?section=activity_public as a `psd`

This is how I'm attempting to read the psd:

`
file = open(psd_location, 'r')	
flat_img = PSDImage.from_stream(file).as_PIL()
`

**Comment by fabiocaccamo** [comment]
This is how I'm attempting to read the psd:
```
psd = PSDImage.load(psd_input_path)
jpg = psd.as_PIL()
jpg.save(jpg_output_path)
```

**Comment by deanblacc** [comment]
@fabiocaccamo interesting. I've used exactly that code and its still throwing the same error.

`Error: Error parsing layer: invalid signature ('\xf3\xfd\xf4\x00')`

Can you confirm that code was successful for you ?

**Comment by fabiocaccamo** [comment]
The problem is in the parsing of some .psd files, with the same code I batched many psd(s), some of them with success and some of them throw the exception, unfortunately I can't upload the .psd(s).

**Comment by deanblacc** [comment]
Appreciate the help you've given anyway, champ !

**Comment by fabiocaccamo** [comment]
@kmike could you investigate this issue using the psd linked by @deanblacc ?

**Comment by kmike** [comment]
Hey @fabiocaccamo @deanblacc @PiOverFour @mociepka  could you please check that the issue is fixed for you in psd-tools master? See https://github.com/psd-tools/psd-tools/pull/62.

**Comment by fabiocaccamo** [comment]
@kmike for me it's fixed, thanks!

I just got the following warning:
```
/psd_tools/decoder/tagged_blocks.py:56: UserWarning: Unknown tagged block (lfxs)
  warnings.warn("Unknown tagged block (%s)" % block.key)
```

**Comment by kmike** [comment]
Thanks for checking that @fabiocaccamo! I've opened a new issue for lfxs blocks.

**Comment by PiOverFour** [comment]
@kmike I tested the same [previously](#issuecomment-222459354) linked image, and though the error does not appear, the `PSDImage` is empty (`psd.layers == []`; `psd.bbox is None`)

I got a warning, probably unrelated:
`psd_tools/decoder/image_resources.py:138: UserWarning: ICC profile is not handled; colors could be incorrect. Please build PIL or Pillow with littlecms/littlecms2 support.
  warnings.warn("ICC profile is not handled; colors could be incorrect. "`

Tested on latest commit `cb13d93f3291a9452417deff39437ba734bf5a81`

**Comment by EvgenKo423** [comment]
@PiOverFour:
Your PSD file is not technically a single layer PSD. It has a "background" layer which Photoshop saves in a composite image. True single layer PSD has a layer saved separately as well.

So, it's OK. And `PSDImage.bbox` is `None` because it's based on layers.
