### ISSUE TITLE
Error generating PIL image from layer

### ISSUE THREAD

**Issue by pythonl1** [psd-tools/psd-tools#51]
When I try to export the layer as a PIL image I get the NameError: name 'frombytes' is not defined.
I have tried installing littlecms and littlecms2 but still I'm getting this warning. I am working debian jessie.
I am new to python and maybe I'm doing something wrong. 

here is the screenshot of the traceback I'm geting:

![screenshot](https://cloud.githubusercontent.com/assets/12238751/9656740/60cc1270-5258-11e5-80cf-80355abe6d6c.png)

**Comment by kmike** [comment]
Could you try updating psd-tools? In recent release line 171 in `pil_support.py` is not the same as in your traceback.

**Comment by pythonl1** [comment]
I am trying to upgrade psd-tools but all I'm getting is requirement already up-to-date.

![screenshot-1](https://cloud.githubusercontent.com/assets/12238751/9658155/d2bcec22-5264-11e5-8a88-fa8410058aa8.png)

I think the problem is that while running the program is using psd-tool modules present in python3.4 directory, but updates are in python 2.7 directories.

Is there anyway to update the modules in python3.4 directory. I'm fairly new user to debian as well. And I'm pretty sure that my speculations might be wrong. Please let me know how to proceed. And thanks for all the help!

**Comment by kmike** [comment]
Yes, it seems that you're updating psd-tools in Python 2, but there is another psd-tools version installed in Python 3. I usually create virtualenvs to prevent such errors; it is not a good practice to install Python packages globally. Check e.g. http://docs.python-guide.org/en/latest/dev/virtualenvs/.

As it doesn't look like a bug in psd-tools I'm closing it.

**Comment by pythonl1** [comment]
OK. Thanks a lot for all the help.
