### ISSUE TITLE
Unable to convert the decoded data into readable format 

### ISSUE THREAD

**Issue by pythonl1** [psd-tools/psd-tools#52]
Hi,

My approach to this problem might be wrong so I'll add the code snippet here. 

```layer_image = layer_count.as_PIL()```
```item['dat'] = str((base64.b64decode((layer_image.tobytes()).decode("utf-8"))))```
 ```print (item['dat'])```

I know that the decoded data is in Unit8Array format. 
I am trying to convert the layer image data to a readable format.

This is the traceback:

```Traceback:
File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in get_response
  132. response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "E:\myproject\myproject\myapp\views.py" in list
  85. item['asdf'] = str((base64.b64decode((layer_image.tobytes()).decode("utf-8"))))

Exception Type: UnicodeDecodeError at /myapp/list/
Exception Value: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by pythonl1** [comment]
@kmike Found a way. Can you please close this issue. And thank you for this amazing tool. Still need to explore a lot.

**Comment by kmike** [comment]
Hey @pythonl1,
Ok, closed!
