### ISSUE TITLE
about psd image data

### ISSUE THREAD

**Issue by ywaby** [psd-tools/psd-tools#59]
i use psdtool to blender addon.
when i read a psd image ,the image dataconfuse me.
i cant undestant 16/32 depth channel.data format, how to convert it to  8bit depth.
can you help me? thanks.

**Comment by kmike** [comment]
hey @ywaby,

psd-tools can return image as a [Pillow](http://pillow.readthedocs.org/) Image object; if you need to process it further please consult with Pillow docs.

**Comment by ywaby** [comment]
i want to decode it direct to pixels of blender image,but blender image's pixels format is 32 depth float data,so i have to tanslate it.but i cant undestant 16/32 depth channel.data format, 
if photoshop r=255 
the data: 
 depth=16: data = 0xff ff ;
 depth=32: data =  0x3f 7f fe ed 
if photoshop r=0 
the data: 
 depth=16: data = 0x00 00 ;
 depth=32: data =  0x37 31 00 00

**Comment by kmike** [comment]
channel.data is not intended to be used directly; there is some complicated logic to convert it to pixel information. psd-tools decompresses it automatically, but the data format depends on channel depth. See https://github.com/psd-tools/psd-tools/blob/master/src/psd_tools/user_api/pil_support.py as an example - it converts all channel data to Pillow data format.
