### ISSUE TITLE
64 bit python support

### ISSUE THREAD

**Issue by minuJeong** [psd-tools/psd-tools#60]
I'm trying to use psd-tools in 64-bit python, because my team is using 64-bit Maya. But it doesn't compiles. Do you have any idea?
Thanks!

error message:
```
Command ""C:\Program Files\Autodesk\Maya2015\bin\mayapy.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\****\\app
(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\****\ap
-externally-managed --compile" failed with error code 1 in c:\users\****\appdata\local\temp\pip-build-krl3up\psd-tools\
```

**Comment by kmike** [comment]
Is it the full error log, or is there more information available? 

Could you try checking out psd-tools from git, setting compile_extension to False [here](https://github.com/psd-tools/psd-tools/blob/6af2c615b3dab6d7f5de1250fb19c91333e82448/setup.py#L105) and installing it from the source code - does it help?

**Comment by minuJeong** [comment]
Thanks, it works like a charm!
