### ISSUE TITLE
Error Merging PSD layers

### ISSUE THREAD

**Issue by juno249** [psd-tools/psd-tools#61]
I got some errors like that when i saved layers in psd file to PNG format. What can i do?
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/psd_tools/user_api/pil_support.py:212: UserWarning: Channel -2 (USER_LAYER_MASK) is not handled
  warnings.warn("Channel %s (%s) is not handled" % (channel_id, ChannelID.name_of(channel_id)))
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/psd_tools/user_api/pil_support.py:162: UserWarning: Unsupported channel type (-2)
  warnings.warn("Unsupported channel type (%d)" % channel_id)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/psd_tools/user_api/pil_support.py:212: UserWarning: Channel -3 (REAL_USER_LAYER_MASK) is not handled
  warnings.warn("Channel %s (%s) is not handled" % (channel_id, ChannelID.name_of(channel_id)))
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/psd_tools/user_api/pil_support.py:162: UserWarning: Unsupported channel type (-3)
  warnings.warn("Unsupported channel type (%d)" % channel_id)
Blend mode is not implemented: LINEAR_BURN
Blend mode is not implemented: SOFT_LIGHT

**Comment by kyamagu** [comment]
Only basic composition is supported. Warnings are shown when there are unsupported data.
