### ISSUE TITLE
Unknown tagged block (lfxs)

### ISSUE THREAD

**Issue by kmike** [psd-tools/psd-tools#63]
From https://github.com/psd-tools/psd-tools/issues/46#issuecomment-266811179:

> /psd_tools/decoder/tagged_blocks.py:56: UserWarning: Unknown tagged block (lfxs)
  warnings.warn("Unknown tagged block (%s)" % block.key)

There is no such blocks in psd specs, but specs have 'lfx2' block (Object-based effects layer info). Maybe it is somewhat related.

**Comment by blancoberg** [comment]
I get that too. Since there is no documentation for that tag, I guess we could just ignore that message :)

**Comment by blancoberg** [comment]
I actually looked into it quickly, and it seems to be the same format as the object based effects, as you were suggesting (lfx2).
Just use the same parsing function as object based effects and you are good to go:

**constants.py**
_in class TaggedBlock add:_ 
`LFXS = b'lfxs'`
  
**layer_effects.py**
_in list _tagged_block_decoders.update({  add:_
`TaggedBlock.LFXS :   layer_effects.decode_object_based`

**Comment by kmike** [comment]
Hey @blancoberg - do you want to make a pull request? :)

**Comment by blancoberg** [comment]
@kmike I'm planning on it :) I'v actually added some more functionality as well. Vector mask parsing, Text engine data parsing and pattern parsing. This is my first time playing around with Python, so it may not look that clean at the moment. I'm gonna see if I can clean up some code during the weekend.

**Comment by kmike** [comment]
@blancoberg very cool!
