### ISSUE TITLE
PSD file resolution unit

### ISSUE THREAD

**Issue by xboomx** [psd-tools/psd-tools#64]
psd-tools is showing h_value and v_value in pix/inch even when unit is set to centimeters. Unit set is decoded correctly.

PSD file:
```
         <tiff:Orientation>1</tiff:Orientation>
         <tiff:YCbCrPositioning>2</tiff:YCbCrPositioning>
         <tiff:XResolution>14300/10000</tiff:XResolution>
         <tiff:YResolution>14300/10000</tiff:YResolution>
         <tiff:ResolutionUnit>3</tiff:ResolutionUnit>
```
ResolutionUnit = 3 => Centimeters (this part is parsed and displayed correctly)
psd-tools read 1.43 pix/cm but display (correctly converted) h_value and v_value as pix/inch.

I read value like this:
psd = PSDImage.load(filename)
psd_res = dict((block.resource_id, block.data) for block in  psd.decoded_data.image_resource_blocks)
print psd_res[ImageResourceID.RESOLUTION_INFO]

Why I have values in pix/inch and unit param: CM ? If values are converted then you should display unit after conversion!?

**Comment by xboomx** [comment]
I'm confused
In psd-tools:
class DisplayResolutionUnit(Enum):
    PIXELS_PER_INCH = 1
    PIXELS_PER_CM = 2

class DimensionUnit(Enum):
    INCH = 1
    CM = 2
    POINT = 3  # 72 points == 1 inch
    PICA = 4   # 6 pica == 1 inch
    COLUMN = 5

But in TIFF Tag ResolutionUnit  documentation i see:
RESUNIT_NONE = 1;
RESUNIT_INCH = 2;
RESUNIT_CENTIMETER = 3;

**Comment by kmike** [comment]
It seems I added it here: https://github.com/psd-tools/psd-tools/commit/fedf4cf81941120521321a735dae6d0c62f97371. Resolution is decoded from binary Photoshop "image resources"; I don't recall where I got the constants from. Specification says "See Appendix A in Photoshop API Guide.pdf.", so probably I found a PDF and copied the constants, and also maybe checked it with GIMP. Where do you see these `<tiff>` tags?

**Comment by xboomx** [comment]
Thank you for your time. 
I have tiff tags in following section of my old PSD file:
       <rdf:Description rdf:about=""
            xmlns:tiff="http://ns.adobe.com/tiff/1.0/">

I checked and it looks like that this file was originally created around year 2004
Ok so if resolution comes from binary part and not some wierd tiff tags then I can live with that. I hope (need to do more tests) that the value will be always in pix/inch. So far it is like this.
