### ISSUE TITLE
padding around layers with vector masks

### ISSUE THREAD

**Issue by blancoberg** [psd-tools/psd-tools#65]
Is there a reason why every layer is exported width transparent padding? 2 pixels from top/left and 1 pixel from bottom/right . Is the data saved that way via photoshop or is it a feature built in psd-tools? It seem to be consistent independing of layer size.

**Comment by blancoberg** [comment]
![image](https://cloud.githubusercontent.com/assets/389305/21552938/5f146002-ce05-11e6-8528-1d3937e71292.png)

**Comment by kyamagu** [comment]
Likely fixed in #91
