### ISSUE TITLE
Sorry this is not Issue Small Doubt !!

### ISSUE THREAD

**Issue by pc8181** [psd-tools/psd-tools#66]
May i use it in Vb.Net if yes then can you provide me that details 
Thanks

**Comment by kmike** [comment]
Hey @pc8181,

Sorry, I have no experience with Vb.Net. 

psd-tools is a Python library; you may a Python script which uses psd-tools to convert PSD file to JSON + PNG files, run it in a subprocess and work with these JSON / PNG files.

**Comment by pc8181** [comment]
thanks for your reply sir really appreciate but i have no idea about python 
anyway thanks for your help
