### ISSUE TITLE
Embedded files (smart objects) API

### ISSUE THREAD

**Issue by flux627** [psd-tools/psd-tools#68]
There is [this pull request](https://github.com/psd-tools/psd-tools/pull/39) that was merged, however there doesn't seem to be any update to the docs. I'm having a hard time seeing exactly how to use this API and what in all is implemented with this PR. Any hints?

**Comment by kyamagu** [comment]
Fixed in #91 

https://psd-tools.readthedocs.io/en/latest/reference/psd_tools.api.smart_object.html
