### ISSUE TITLE
Layer group `blend_mode` showing `norm` when set to `pass`

### ISSUE THREAD

**Issue by flux627** [psd-tools/psd-tools#69]
Blend mode for layer groups both show as `norm` using psd-tools, however in Photoshop `pass.psd` shows Pass Through and `no-pass.psd` shows Normal. A quick diff in a hex editor shows that there is change from `norm` to `pass`, however I don't know how to read the surrounding context.

My use-case requires this distinction, any help would be greatly appreciated.

[pass-tests.zip](https://github.com/psd-tools/psd-tools/files/752135/pass-tests.zip)

**Comment by kyamagu** [comment]
Fixed in #116
