### ISSUE TITLE
Replace linked file on smart object layer

### ISSUE THREAD

**Issue by nikmauro** [psd-tools/psd-tools#89]

**Comment by nikmauro** [comment]
```python
<psdimage: size=495x425, layer_count=2>
  <smartobject: u'Design', size=183x324, x=15, y=45, mask=<mask: size=371x388, x=107, y=21>, linked=<u'CustomDesign.png', type=data, 30796 bytes>>
  <pixel: u'Mug', size=373x392, x=107, y=19>
```

**Comment by kyamagu** [comment]
Currently write/edit support is not available for smart objects

**Comment by angelor858** [comment]
is there write/edit support yet?

**Comment by harkalygergo** [comment]
Is this request still not ready? I am also looking for solution to change / replace linked file to an external file with psd-tools Python script.

**Comment by icvorovic** [comment]
Hey guys, did you have a chance to try [Dynamic Mockups](https://dynamicmockups.com/)?
They implemented an [application](https://app.dynamicmockups.com/) and [API](https://dynamicmockups.com/api/) that recognizes smart objects from PSD mockups and give you possibility to define colors and design assets for each of them. There is a great feature that create output variations across all smart objects and their colors and asset deisgns.

**Comment by harkalygergo** [comment]
"They". You are part of Dynamic Mockups project based on this: https://www.linkedin.com/posts/dynamic-mockups_jako-smo-u%C5%A1li-u-ovu-godinu-dynamic-mockups-activity-7162909515003240453-34f8

So this comment is an own ad. It's not a problem, but I don't find pricing on website.

**Comment by milqnomadu** [comment]
> Is this request still not ready? I am also looking for solution to change / replace linked file to an external file with psd-tools Python script (or any other automated script).

Hey did you find any solution?

**Comment by cstamati** [comment]
I would love this!
