### ISSUE TITLE
Question: layer.descendants() visibility

### ISSUE THREAD

**Issue by Constuelo** [psd-tools/psd-tools#92]
[test.zip](https://github.com/psd-tools/psd-tools/files/2885460/test.zip)

I am trying iterate through a psd layers using .descendants()

However i want to not include layers inside an invisible group

In the below code it will not print the inivisible layer, however will print anything inside that group

Is there a known / simple way i can go about this?

```
    for layer in reversed(list(psd_load.descendants())):
        if layer.visible:
            print(layer)
```

**Comment by kyamagu** [comment]
@Constuelo Instead of `visible` property, use `is_visible()` method

**Comment by Constuelo** [comment]
Thanks for this, it's clearly in the documentation but i missed it
