### ISSUE TITLE
How to get the alignment of the text

### ISSUE THREAD

**Issue by rxy007** [psd-tools/psd-tools#94]
hi:
   How to get the alignment of the text? in type layer.
thanks!

**Comment by kyamagu** [comment]
@rxy007 You can check `engine_dict` property of the TypeLayer. Some of the entry corresponds paragraph information.

**Comment by rxy007** [comment]
> @rxy007 You can check `engine_dict` property of the TypeLayer. Some of the entry corresponds paragraph information.

![image](https://user-images.githubusercontent.com/21076858/53385082-2dff9100-39b8-11e9-821f-e627bcdd0c0a.png)
i am check engine_dict, seem StyleRunAlignment like alignment, but it's value is 5, I don't know what this stands for.

**Comment by kyamagu** [comment]
@rxy007 Likely an index for one of the possible alignment type. Unfortunately only Adobe knows the real meaning of every piece of the bits in PSD file. Perhaps you can confirm `5` indicates some alignment type?

**Comment by rxy007** [comment]
> @rxy007 Likely an index for one of the possible alignment type. Unfortunately only Adobe knows the real meaning of every piece of the bits in PSD file. Perhaps you can confirm `5` indicates some alignment type?

e, no, i changed alignment type and this value is still 5, but psd.js and psd.rb is suceessed, 
![image](https://user-images.githubusercontent.com/21076858/53386176-20e4a100-39bc-11e9-85ff-09bc6bc8e201.png)
Get the alignment of each line. 
thanks!

**Comment by kyamagu** [comment]
@rxy007 Can you check which field those tools extract? `Justification` seems relevant but I'm not sure.

**Comment by rxy007** [comment]
> @rxy007 Can you check which field those tools extract? `Justification` seems relevant but I'm not sure.

You seem to be right， Justification seems is alignment. 
and i'm sorry, I am not very familiar with node and ruby, 
github: 
node https://github.com/meltingice/psd.js
ruby https://github.com/layervault/psd.rb
and very thank you for help me.
