### ISSUE TITLE
Unknown ClassID warnings

### ISSUE THREAD

**Issue by zewt** [psd-tools/psd-tools#98]
I'm getting some unknown ClassID warnings (DfsM, SprS, SprR, SDHz).  Nothing surprising there, but would like to quiet them.  I thought about just adding them to the list, but that seems like a bad approach, since there are tons of them looking at OLEConsts.h, and I think smart filters can encode arbitrary IDs coming from filter plugin settings.

The warning is probably sometimes useful since it indicates unsupported features in the PSD, but it's usually just noise.  Maybe it should only go to debug?

**Comment by kyamagu** [comment]
@zewt Great point. This part is far from complete and perhaps should go to debug logs. Will incorporate in the next release.

I have not been aware of the C header files in photoshop plugin SDK. Thanks ;)

**Comment by zewt** [comment]
FYI, I checked and those blocks do have class IDs from plugins, so it's not actually possible to have a complete list.

**Comment by kyamagu** [comment]
Fixed in #99
